// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: IAQ_Monitor_UI

#ifndef _IAQ_MONITOR_UI_UI_H
#define _IAQ_MONITOR_UI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"


// SCREEN: ui_MainScreen
void ui_MainScreen_screen_init(void);
extern lv_obj_t * ui_MainScreen;
extern lv_obj_t * ui_MainScreen_Container1;
extern lv_obj_t * ui_MainScreen_SensirionLogo;
extern lv_obj_t * ui_MainScreen_Label1;
extern lv_obj_t * ui_MainScreen_TilePM;
extern lv_obj_t * ui_MainScreen_TileCO2;
extern lv_obj_t * ui_MainScreen_TileVOC;
extern lv_obj_t * ui_MainScreen_TileNOx;
extern lv_obj_t * ui_MainScreen_TileT;
extern lv_obj_t * ui_MainScreen_TileRH;
// CUSTOM VARIABLES

// SCREEN: ui_PMScreen
void ui_PMScreen_screen_init(void);
extern lv_obj_t * ui_PMScreen;
extern lv_obj_t * ui_PMScreen_Panel1;
extern lv_obj_t * ui_PMScreen_PMValues;
extern lv_obj_t * ui_PMScreen_PM1;
extern lv_obj_t * ui_PMScreen_Pollutant;
extern lv_obj_t * ui_PMScreen_Value;
extern lv_obj_t * ui_PMScreen_PM25;
extern lv_obj_t * ui_PMScreen_Pollutant1;
extern lv_obj_t * ui_PMScreen_Value1;
extern lv_obj_t * ui_PMScreen_PM4;
extern lv_obj_t * ui_PMScreen_Pollutant2;
extern lv_obj_t * ui_PMScreen_Value2;
extern lv_obj_t * ui_PMScreen_PM10;
extern lv_obj_t * ui_PMScreen_Pollutant3;
extern lv_obj_t * ui_PMScreen_Value3;
extern lv_obj_t * ui_PMScreen_Unit;
extern lv_obj_t * ui_PMScreen_PMChart;
extern lv_obj_t * ui_PMScreen_XMinValue;
extern lv_obj_t * ui_PMScreen_XMaxValue;
extern lv_obj_t * ui_PMScreen_YMinValue;
extern lv_obj_t * ui_PMScreen_YMaxValue;
// CUSTOM VARIABLES

// SCREEN: ui_CO2Screen
void ui_CO2Screen_screen_init(void);
extern lv_obj_t * ui_CO2Screen;
extern lv_obj_t * ui_CO2Screen_Panel;
extern lv_obj_t * ui_CO2Screen_Container;
extern lv_obj_t * ui_CO2Screen_Title;
extern lv_obj_t * ui_CO2Screen_Symbol;
extern lv_obj_t * ui_CO2Screen_Pollutant;
extern lv_obj_t * ui_CO2Screen_Value;
extern lv_obj_t * ui_CO2Screen_Unit;
extern lv_obj_t * ui_CO2Screen_CO2Chart;
extern lv_obj_t * ui_CO2Screen_XMinValue;
extern lv_obj_t * ui_CO2Screen_XMaxValue;
extern lv_obj_t * ui_CO2Screen_YMinValue;
extern lv_obj_t * ui_CO2Screen_YMaxValue;
// CUSTOM VARIABLES

// SCREEN: ui_VOCScreen
void ui_VOCScreen_screen_init(void);
extern lv_obj_t * ui_VOCScreen;
extern lv_obj_t * ui_VOCScreen_Panel;
extern lv_obj_t * ui_VOCScreen_Container;
extern lv_obj_t * ui_VOCScreen_Title;
extern lv_obj_t * ui_VOCScreen_Symbol;
extern lv_obj_t * ui_VOCScreen_Pollutant;
extern lv_obj_t * ui_VOCScreen_Value;
extern lv_obj_t * ui_VOCScreen_Unit;
extern lv_obj_t * ui_VOCScreen_VOCChart;
extern lv_obj_t * ui_VOCScreen_XMinValue;
extern lv_obj_t * ui_VOCScreen_XMaxValue;
extern lv_obj_t * ui_VOCScreen_YMinValue;
extern lv_obj_t * ui_VOCScreen_YMaxValue;
// CUSTOM VARIABLES

// SCREEN: ui_NOxScreen
void ui_NOxScreen_screen_init(void);
extern lv_obj_t * ui_NOxScreen;
extern lv_obj_t * ui_NOxScreen_Panel;
extern lv_obj_t * ui_NOxScreen_Container;
extern lv_obj_t * ui_NOxScreen_Title;
extern lv_obj_t * ui_NOxScreen_Symbol;
extern lv_obj_t * ui_NOxScreen_Pollutant;
extern lv_obj_t * ui_NOxScreen_Value;
extern lv_obj_t * ui_NOxScreen_Unit;
extern lv_obj_t * ui_NOxScreen_NOxChart;
extern lv_obj_t * ui_NOxScreen_XMinValue;
extern lv_obj_t * ui_NOxScreen_XMaxValue;
extern lv_obj_t * ui_NOxScreen_YMinValue;
extern lv_obj_t * ui_NOxScreen_YMaxValue;
// CUSTOM VARIABLES

// SCREEN: ui_TempScreen
void ui_TempScreen_screen_init(void);
extern lv_obj_t * ui_TempScreen;
extern lv_obj_t * ui_TempScreen_Panel;
extern lv_obj_t * ui_TempScreen_Container;
extern lv_obj_t * ui_TempScreen_Title;
extern lv_obj_t * ui_TempScreen_Symbol;
extern lv_obj_t * ui_TempScreen_Pollutant;
extern lv_obj_t * ui_TempScreen_Value;
extern lv_obj_t * ui_TempScreen_Unit;
extern lv_obj_t * ui_TempScreen_TempChart;
extern lv_obj_t * ui_TempScreen_XMinValue;
extern lv_obj_t * ui_TempScreen_XMaxValue;
extern lv_obj_t * ui_TempScreen_YMinValue;
extern lv_obj_t * ui_TempScreen_YMaxValue;
// CUSTOM VARIABLES

// SCREEN: ui_RHScreen
void ui_RHScreen_screen_init(void);
extern lv_obj_t * ui_RHScreen;
extern lv_obj_t * ui_RHScreen_Panel;
extern lv_obj_t * ui_RHScreen_Container;
extern lv_obj_t * ui_RHScreen_Title;
extern lv_obj_t * ui_RHScreen_Symbol;
extern lv_obj_t * ui_RHScreen_Pollutant;
extern lv_obj_t * ui_RHScreen_Value;
extern lv_obj_t * ui_RHScreen_Unit;
extern lv_obj_t * ui_RHScreen_RHChart;
extern lv_obj_t * ui_RHScreen_XMinValue;
extern lv_obj_t * ui_RHScreen_XMaxValue;
extern lv_obj_t * ui_RHScreen_YMinValue;
extern lv_obj_t * ui_RHScreen_YMaxValue;
// CUSTOM VARIABLES

// SCREEN: ui_SettingsScreen
void ui_SettingsScreen_screen_init(void);
extern lv_obj_t * ui_SettingsScreen;
extern lv_obj_t * ui_SettingsScreen_Panel;
extern lv_obj_t * ui_SettingsScreen_Pollutant;
extern lv_obj_t * ui_SettingsScreen_Symbol;
extern lv_obj_t * ui_SettingsScreen_Container;
extern lv_obj_t * ui_SettingsScreen_Label;
extern lv_obj_t * ui_SettingsScreen_Image;

// SCREEN: ui_FRCScreen
void ui_FRCScreen_screen_init(void);
extern lv_obj_t * ui_FRCScreen;
extern lv_obj_t * ui_FRCScreen_Container;
extern lv_obj_t * ui_FRCScreen_ContainerUp;
extern lv_obj_t * ui_FRCScreen_LabelUp;
extern lv_obj_t * ui_FRCScreen_ImageUp;
extern lv_obj_t * ui_FRCScreen_Panel;
extern lv_obj_t * ui_FRCScreen_Title;
extern lv_obj_t * ui_FRCScreen_TargetValue;
extern lv_obj_t * ui_FRCScreen_Unit;
extern lv_obj_t * ui_FRCScreen_ContainerDown;
extern lv_obj_t * ui_FRCScreen_ImageDown;
extern lv_obj_t * ui_FRCScreen_LabelDown;
extern lv_obj_t * ui_FRCScreen_ContainerRight;
extern lv_obj_t * ui_FRCScreen_LabelRight;
extern lv_obj_t * ui_FRCScreen_ImageRight;
extern lv_obj_t * ui_FRCScreen_ContainerLeft;
extern lv_obj_t * ui_FRCScreen_ImageLeft;
extern lv_obj_t * ui_FRCScreen_LabelLeft;
extern lv_obj_t * ui_FRCScreen_PanelInfo;
extern lv_obj_t * ui_FRCScreen_LabelInfo;
extern lv_obj_t * ui_FRCScreen_LabelRuntime;
// CUSTOM VARIABLES

// SCREEN: ui_AltitudeScreen
void ui_AltitudeScreen_screen_init(void);
extern lv_obj_t * ui_AltitudeScreen;
extern lv_obj_t * ui_AltitudeScreen_Container;
extern lv_obj_t * ui_AltitudeScreen_ContainerUp;
extern lv_obj_t * ui_AltitudeScreen_LabelUp;
extern lv_obj_t * ui_AltitudeScreen_ImageUp;
extern lv_obj_t * ui_AltitudeScreen_Panel;
extern lv_obj_t * ui_AltitudeScreen_Title;
extern lv_obj_t * ui_AltitudeScreen_TargetValue;
extern lv_obj_t * ui_AltitudeScreen_Unit;
extern lv_obj_t * ui_AltitudeScreen_ContainerDown;
extern lv_obj_t * ui_AltitudeScreen_ImageDown;
extern lv_obj_t * ui_AltitudeScreen_LabelDown;
extern lv_obj_t * ui_AltitudeScreen_ContainerRight;
extern lv_obj_t * ui_AltitudeScreen_LabelRight;
extern lv_obj_t * ui_AltitudeScreen_ImageRight;
extern lv_obj_t * ui_AltitudeScreen_ContainerLeft;
extern lv_obj_t * ui_AltitudeScreen_ImageLeft;
extern lv_obj_t * ui_AltitudeScreen_LabelLeft;
// CUSTOM VARIABLES

// SCREEN: ui_ChartTimeScreen
void ui_ChartTimeScreen_screen_init(void);
extern lv_obj_t * ui_ChartTimeScreen;
extern lv_obj_t * ui_ChartTimeScreen_Container;
extern lv_obj_t * ui_ChartTimeScreen_ContainerUp;
extern lv_obj_t * ui_ChartTimeScreen_ImageUp;
extern lv_obj_t * ui_ChartTimeScreen_Panel;
extern lv_obj_t * ui_ChartTimeScreen_Title;
extern lv_obj_t * ui_ChartTimeScreen_CheckboxShort;
extern lv_obj_t * ui_ChartTimeScreen_CheckboxMedium;
extern lv_obj_t * ui_ChartTimeScreen_CheckboxLong;
extern lv_obj_t * ui_ChartTimeScreen_ContainerDown;
extern lv_obj_t * ui_ChartTimeScreen_ImageDown;
extern lv_obj_t * ui_ChartTimeScreen_ContainerRight;
extern lv_obj_t * ui_ChartTimeScreen_LabelRight;
extern lv_obj_t * ui_ChartTimeScreen_ImageRight;
extern lv_obj_t * ui_ChartTimeScreen_ContainerLeft;
extern lv_obj_t * ui_ChartTimeScreen_ImageLeft;
extern lv_obj_t * ui_ChartTimeScreen_LabelLeft;
// CUSTOM VARIABLES

// SCREEN: ui_BrightnessScreen
void ui_BrightnessScreen_screen_init(void);
extern lv_obj_t * ui_BrightnessScreen;
extern lv_obj_t * ui_BrightnessScreen_Container;
extern lv_obj_t * ui_BrightnessScreen_ContainerUp;
extern lv_obj_t * ui_BrightnessScreen_ImageUp;
extern lv_obj_t * ui_BrightnessScreen_Panel;
extern lv_obj_t * ui_BrightnessScreen_Title;
extern lv_obj_t * ui_BrightnessScreen_Checkbox100;
extern lv_obj_t * ui_BrightnessScreen_Checkbox75;
extern lv_obj_t * ui_BrightnessScreen_Checkbox50;
extern lv_obj_t * ui_BrightnessScreen_Checkbox25;
extern lv_obj_t * ui_BrightnessScreen_ContainerDown;
extern lv_obj_t * ui_BrightnessScreen_ImageDown;
extern lv_obj_t * ui_BrightnessScreen_ContainerRight;
extern lv_obj_t * ui_BrightnessScreen_LabelRight;
extern lv_obj_t * ui_BrightnessScreen_ImageRight;
extern lv_obj_t * ui_BrightnessScreen_ContainerLeft;
extern lv_obj_t * ui_BrightnessScreen_ImageLeft;
extern lv_obj_t * ui_BrightnessScreen_LabelLeft;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_sensirion_logo_rgb_green_small_png);    // assets/Sensirion_Logo_RGB_green_small.png
LV_IMG_DECLARE(ui_img_grip_png);    // assets/grip.png
LV_IMG_DECLARE(ui_img_wind_png);    // assets/wind.png
LV_IMG_DECLARE(ui_img_510121354);    // assets/flask-conical.png
LV_IMG_DECLARE(ui_img_741524973);    // assets/flame-kindling.png
LV_IMG_DECLARE(ui_img_thermometer_png);    // assets/thermometer.png
LV_IMG_DECLARE(ui_img_droplets_png);    // assets/droplets.png
LV_IMG_DECLARE(ui_img_wind_white_png);    // assets/wind_white.png
LV_IMG_DECLARE(ui_img_417669948);    // assets/flask-conical_white.png
LV_IMG_DECLARE(ui_img_238700877);    // assets/flame-kindling_white.png
LV_IMG_DECLARE(ui_img_thermometer_white_png);    // assets/thermometer_white.png
LV_IMG_DECLARE(ui_img_droplets_white_png);    // assets/droplets_white.png
LV_IMG_DECLARE(ui_img_cog_png);    // assets/cog.png
LV_IMG_DECLARE(ui_img_718623388);    // assets/corner-right-down.png
LV_IMG_DECLARE(ui_img_816914973);    // assets/arrow-big-up.png
LV_IMG_DECLARE(ui_img_810620936);    // assets/arrow-big-down.png
LV_IMG_DECLARE(ui_img_1346862293);    // assets/corner-left-down.png
LV_IMG_DECLARE(ui_img_blank_png);    // assets/blank.png

// FONTS
LV_FONT_DECLARE(ui_font_Arial_Black_18);
LV_FONT_DECLARE(ui_font_Arial_Black_22);
LV_FONT_DECLARE(ui_font_Arial_Bold_13);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
