// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: IAQ_Monitor_UI

#ifndef _IAQ_MONITOR_UI_UI_H
#define _IAQ_MONITOR_UI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"

// SCREEN: ui_MainScreen
void ui_MainScreen_screen_init(void);
extern lv_obj_t * ui_MainScreen;
extern lv_obj_t * ui_MainScreen_Container1;
extern lv_obj_t * ui_MainScreen_TilePM;
extern lv_obj_t * ui_MainScreen_TileRH;
extern lv_obj_t * ui_MainScreen_TileT;
extern lv_obj_t * ui_MainScreen_TileNOx;
extern lv_obj_t * ui_MainScreen_TileVOC;
extern lv_obj_t * ui_MainScreen_TileCO2;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// FONTS
LV_FONT_DECLARE(ui_font_Arial_Black_22);
LV_FONT_DECLARE(ui_font_Arial_Bold_13);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
