// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: IAQ_Monitor_UI

#include "ui.h"

void ui_comp_Kachel_create_hook(lv_obj_t * comp)
{
}

void ui_comp_Tile_create_hook(lv_obj_t * comp)
{
}
