// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: IAQ_Monitor_UI

#include "ui.h"

// COMPONENT Tile

lv_obj_t * ui_Tile_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Tile;
    cui_Tile = lv_obj_create(comp_parent);
    lv_obj_set_width(cui_Tile, 79);
    lv_obj_set_height(cui_Tile, 85);
    lv_obj_set_x(cui_Tile, 4);
    lv_obj_set_y(cui_Tile, -4);
    lv_obj_set_align(cui_Tile, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_clear_flag(cui_Tile, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_Tile, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_Tile, lv_color_hex(0x182831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Tile, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(cui_Tile, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Value;
    cui_Value = lv_label_create(cui_Tile);
    lv_obj_set_width(cui_Value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_Value, LV_ALIGN_CENTER);
    lv_label_set_long_mode(cui_Value, LV_LABEL_LONG_CLIP);
    lv_label_set_text(cui_Value, "100.1");
    lv_obj_set_style_text_font(cui_Value, &ui_font_Arial_Black_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Indicator;
    cui_Indicator = lv_obj_create(cui_Tile);
    lv_obj_set_width(cui_Indicator, 12);
    lv_obj_set_height(cui_Indicator, 12);
    lv_obj_set_x(cui_Indicator, -8);
    lv_obj_set_y(cui_Indicator, 8);
    lv_obj_set_align(cui_Indicator, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_clear_flag(cui_Indicator, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_Indicator, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_Indicator, lv_color_hex(0x20C65A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Indicator, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(cui_Indicator, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_Indicator, lv_color_hex(0xFF7700), LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_bg_opa(cui_Indicator, 255, LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_bg_color(cui_Indicator, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_set_style_bg_opa(cui_Indicator, 255, LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_set_style_bg_color(cui_Indicator, lv_color_hex(0x002EFF), LV_PART_MAIN | LV_STATE_USER_3);
    lv_obj_set_style_bg_opa(cui_Indicator, 255, LV_PART_MAIN | LV_STATE_USER_3);

    lv_obj_t * cui_Polutant;
    cui_Polutant = lv_label_create(cui_Tile);
    lv_obj_set_width(cui_Polutant, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Polutant, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Polutant, -8);
    lv_obj_set_y(cui_Polutant, -8);
    lv_label_set_text(cui_Polutant, "VOC");
    lv_obj_set_style_text_font(cui_Polutant, &ui_font_Arial_Bold_13, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Unit;
    cui_Unit = lv_label_create(cui_Tile);
    lv_obj_set_width(cui_Unit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Unit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Unit, 8);
    lv_obj_set_y(cui_Unit, 8);
    lv_obj_set_align(cui_Unit, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(cui_Unit, "Index");
    lv_obj_set_style_text_font(cui_Unit, &ui_font_Arial_Bold_13, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_TILE_NUM);
    children[UI_COMP_TILE_TILE] = cui_Tile;
    children[UI_COMP_TILE_VALUE] = cui_Value;
    children[UI_COMP_TILE_INDICATOR] = cui_Indicator;
    children[UI_COMP_TILE_POLUTANT] = cui_Polutant;
    children[UI_COMP_TILE_UNIT] = cui_Unit;
    lv_obj_add_event_cb(cui_Tile, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Tile, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_Tile_create_hook(cui_Tile);
    return cui_Tile;
}

