// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: IAQ_Monitor_UI

#include "ui.h"

void ui_FRCScreen_screen_init(void)
{
    ui_FRCScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_FRCScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_FRCScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_FRCScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FRCScreen_Label2 = lv_label_create(ui_FRCScreen);
    lv_obj_set_width(ui_FRCScreen_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FRCScreen_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FRCScreen_Label2, 2);
    lv_obj_set_y(ui_FRCScreen_Label2, -10);
    lv_obj_set_align(ui_FRCScreen_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_FRCScreen_Label2, "400ppm");
    lv_obj_set_style_text_font(ui_FRCScreen_Label2, &ui_font_Arial_Black_22, LV_PART_MAIN | LV_STATE_DEFAULT);

}
