// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: Settings

#include "ui.h"

void ui_FRCScreen_screen_init(void)
{
    ui_FRCScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_FRCScreen, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE |
                      LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM);     /// Flags
    lv_obj_set_scrollbar_mode(ui_FRCScreen, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_scroll_snap_x(ui_FRCScreen, LV_SCROLL_SNAP_CENTER);
    lv_obj_set_scroll_snap_y(ui_FRCScreen, LV_SCROLL_SNAP_CENTER);
    lv_obj_set_style_bg_color(ui_FRCScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_FRCScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_FRCScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_FRCScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_FRCScreen, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_FRCScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FRCScreen_Container = lv_obj_create(ui_FRCScreen);
    lv_obj_remove_style_all(ui_FRCScreen_Container);
    lv_obj_set_width(ui_FRCScreen_Container, lv_pct(100));
    lv_obj_set_height(ui_FRCScreen_Container, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_FRCScreen_Container, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_FRCScreen_Container, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_FRCScreen_Container, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_FRCScreen_Container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_FRCScreen_ContainerUp = lv_obj_create(ui_FRCScreen_Container);
    lv_obj_remove_style_all(ui_FRCScreen_ContainerUp);
    lv_obj_set_width(ui_FRCScreen_ContainerUp, 160);
    lv_obj_set_height(ui_FRCScreen_ContainerUp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FRCScreen_ContainerUp, 23);
    lv_obj_set_y(ui_FRCScreen_ContainerUp, -106);
    lv_obj_set_align(ui_FRCScreen_ContainerUp, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_FRCScreen_ContainerUp, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_FRCScreen_ContainerUp, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_FRCScreen_ContainerUp, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_FRCScreen_ContainerUp, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_FRCScreen_ContainerUp, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_FRCScreen_ContainerUp, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_FRCScreen_ContainerUp, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_FRCScreen_ContainerUp, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_FRCScreen_ContainerUp, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_FRCScreen_ContainerUp, &ui_font_Arial_Bold_13, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FRCScreen_LabelUp = lv_label_create(ui_FRCScreen_ContainerUp);
    lv_obj_set_width(ui_FRCScreen_LabelUp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FRCScreen_LabelUp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_FRCScreen_LabelUp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_FRCScreen_LabelUp, "+10ppm");

    ui_FRCScreen_ImageUp = lv_img_create(ui_FRCScreen_ContainerUp);
    lv_img_set_src(ui_FRCScreen_ImageUp, &ui_img_816914973);
    lv_obj_set_width(ui_FRCScreen_ImageUp, 20);
    lv_obj_set_height(ui_FRCScreen_ImageUp, 20);
    lv_obj_set_align(ui_FRCScreen_ImageUp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_FRCScreen_ImageUp, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_FRCScreen_ImageUp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_FRCScreen_Panel = lv_obj_create(ui_FRCScreen_Container);
    lv_obj_set_width(ui_FRCScreen_Panel, 166);
    lv_obj_set_height(ui_FRCScreen_Panel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_FRCScreen_Panel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_FRCScreen_Panel, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_FRCScreen_Panel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_FRCScreen_Panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_FRCScreen_Panel, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_FRCScreen_Panel, lv_color_hex(0x182831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_FRCScreen_Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_FRCScreen_Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_FRCScreen_Panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_FRCScreen_Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_FRCScreen_Panel, &ui_font_Arial_Bold_13, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FRCScreen_Title = lv_label_create(ui_FRCScreen_Panel);
    lv_obj_set_width(ui_FRCScreen_Title, lv_pct(100));
    lv_obj_set_height(ui_FRCScreen_Title, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_FRCScreen_Title, LV_ALIGN_CENTER);
    lv_label_set_text(ui_FRCScreen_Title, "Forced Recalibration of CO2 Sensor");
    lv_obj_set_style_text_align(ui_FRCScreen_Title, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FRCScreen_TargetValue = lv_label_create(ui_FRCScreen_Panel);
    lv_obj_set_width(ui_FRCScreen_TargetValue, lv_pct(100));
    lv_obj_set_height(ui_FRCScreen_TargetValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FRCScreen_TargetValue, -2);
    lv_obj_set_y(ui_FRCScreen_TargetValue, 0);
    lv_obj_set_align(ui_FRCScreen_TargetValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_FRCScreen_TargetValue, "400");
    lv_obj_set_style_text_color(ui_FRCScreen_TargetValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_FRCScreen_TargetValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_FRCScreen_TargetValue, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_FRCScreen_TargetValue, &ui_font_Arial_Black_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FRCScreen_Unit = lv_label_create(ui_FRCScreen_Panel);
    lv_obj_set_width(ui_FRCScreen_Unit, lv_pct(100));
    lv_obj_set_height(ui_FRCScreen_Unit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_FRCScreen_Unit, LV_ALIGN_CENTER);
    lv_label_set_text(ui_FRCScreen_Unit, "ppm");
    lv_obj_set_style_text_align(ui_FRCScreen_Unit, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FRCScreen_ContainerDown = lv_obj_create(ui_FRCScreen_Container);
    lv_obj_remove_style_all(ui_FRCScreen_ContainerDown);
    lv_obj_set_width(ui_FRCScreen_ContainerDown, lv_pct(100));
    lv_obj_set_height(ui_FRCScreen_ContainerDown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FRCScreen_ContainerDown, 23);
    lv_obj_set_y(ui_FRCScreen_ContainerDown, -106);
    lv_obj_set_align(ui_FRCScreen_ContainerDown, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_FRCScreen_ContainerDown, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_FRCScreen_ContainerDown, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_FRCScreen_ContainerDown, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_FRCScreen_ContainerDown, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_FRCScreen_ContainerDown, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_FRCScreen_ContainerDown, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_FRCScreen_ContainerDown, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_FRCScreen_ContainerDown, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_FRCScreen_ContainerDown, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_FRCScreen_ContainerDown, &ui_font_Arial_Bold_13, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FRCScreen_ImageDown = lv_img_create(ui_FRCScreen_ContainerDown);
    lv_img_set_src(ui_FRCScreen_ImageDown, &ui_img_810620936);
    lv_obj_set_width(ui_FRCScreen_ImageDown, 20);
    lv_obj_set_height(ui_FRCScreen_ImageDown, 20);
    lv_obj_set_align(ui_FRCScreen_ImageDown, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_FRCScreen_ImageDown, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_FRCScreen_ImageDown, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_FRCScreen_LabelDown = lv_label_create(ui_FRCScreen_ContainerDown);
    lv_obj_set_width(ui_FRCScreen_LabelDown, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FRCScreen_LabelDown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_FRCScreen_LabelDown, LV_ALIGN_CENTER);
    lv_label_set_text(ui_FRCScreen_LabelDown, "-10ppm");

    ui_FRCScreen_ContainerRight = lv_obj_create(ui_FRCScreen);
    lv_obj_remove_style_all(ui_FRCScreen_ContainerRight);
    lv_obj_set_width(ui_FRCScreen_ContainerRight, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FRCScreen_ContainerRight, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FRCScreen_ContainerRight, -5);
    lv_obj_set_y(ui_FRCScreen_ContainerRight, -5);
    lv_obj_set_align(ui_FRCScreen_ContainerRight, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_set_flex_flow(ui_FRCScreen_ContainerRight, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_FRCScreen_ContainerRight, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_FRCScreen_ContainerRight, LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags
    lv_obj_clear_flag(ui_FRCScreen_ContainerRight, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_FRCScreen_LabelRight = lv_label_create(ui_FRCScreen_ContainerRight);
    lv_obj_set_width(ui_FRCScreen_LabelRight, 86);
    lv_obj_set_height(ui_FRCScreen_LabelRight, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_FRCScreen_LabelRight, LV_ALIGN_CENTER);
    lv_label_set_text(ui_FRCScreen_LabelRight, "long press to adjust value");
    lv_obj_set_style_text_align(ui_FRCScreen_LabelRight, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_FRCScreen_LabelRight, &ui_font_Arial_Bold_13, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FRCScreen_ImageRight = lv_img_create(ui_FRCScreen_ContainerRight);
    lv_img_set_src(ui_FRCScreen_ImageRight, &ui_img_718623388);
    lv_obj_set_width(ui_FRCScreen_ImageRight, 28);
    lv_obj_set_height(ui_FRCScreen_ImageRight, 28);
    lv_obj_set_align(ui_FRCScreen_ImageRight, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_FRCScreen_ImageRight, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_FRCScreen_ImageRight, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_FRCScreen_ContainerLeft = lv_obj_create(ui_FRCScreen);
    lv_obj_remove_style_all(ui_FRCScreen_ContainerLeft);
    lv_obj_set_width(ui_FRCScreen_ContainerLeft, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FRCScreen_ContainerLeft, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FRCScreen_ContainerLeft, 5);
    lv_obj_set_y(ui_FRCScreen_ContainerLeft, -40);
    lv_obj_set_align(ui_FRCScreen_ContainerLeft, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_set_flex_flow(ui_FRCScreen_ContainerLeft, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_FRCScreen_ContainerLeft, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_FRCScreen_ContainerLeft, LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags
    lv_obj_clear_flag(ui_FRCScreen_ContainerLeft, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_FRCScreen_ContainerLeft, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_FRCScreen_ContainerLeft, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FRCScreen_ImageLeft = lv_img_create(ui_FRCScreen_ContainerLeft);
    lv_img_set_src(ui_FRCScreen_ImageLeft, &ui_img_1346862293);
    lv_obj_set_width(ui_FRCScreen_ImageLeft, 28);
    lv_obj_set_height(ui_FRCScreen_ImageLeft, 28);
    lv_obj_set_align(ui_FRCScreen_ImageLeft, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_FRCScreen_ImageLeft, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_FRCScreen_ImageLeft, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_FRCScreen_LabelLeft = lv_label_create(ui_FRCScreen_ContainerLeft);
    lv_obj_set_width(ui_FRCScreen_LabelLeft, 90);
    lv_obj_set_height(ui_FRCScreen_LabelLeft, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_FRCScreen_LabelLeft, LV_ALIGN_CENTER);
    lv_label_set_text(ui_FRCScreen_LabelLeft, "long press to exit settings");
    lv_obj_set_style_text_align(ui_FRCScreen_LabelLeft, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_FRCScreen_LabelLeft, &ui_font_Arial_Bold_13, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FRCScreen_PanelInfo = lv_obj_create(ui_FRCScreen);
    lv_obj_set_width(ui_FRCScreen_PanelInfo, 170);
    lv_obj_set_height(ui_FRCScreen_PanelInfo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FRCScreen_PanelInfo, 0);
    lv_obj_set_y(ui_FRCScreen_PanelInfo, 47);
    lv_obj_set_align(ui_FRCScreen_PanelInfo, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_FRCScreen_PanelInfo, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_FRCScreen_PanelInfo, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_END);
    lv_obj_clear_flag(ui_FRCScreen_PanelInfo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_FRCScreen_PanelInfo, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_FRCScreen_PanelInfo, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_FRCScreen_PanelInfo, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_FRCScreen_PanelInfo, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_FRCScreen_PanelInfo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_FRCScreen_PanelInfo, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_FRCScreen_PanelInfo, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_FRCScreen_PanelInfo, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_FRCScreen_PanelInfo, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FRCScreen_LabelInfo = lv_label_create(ui_FRCScreen_PanelInfo);
    lv_obj_set_width(ui_FRCScreen_LabelInfo, 160);
    lv_obj_set_height(ui_FRCScreen_LabelInfo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FRCScreen_LabelInfo, 0);
    lv_obj_set_y(ui_FRCScreen_LabelInfo, 30);
    lv_obj_set_align(ui_FRCScreen_LabelInfo, LV_ALIGN_CENTER);
    lv_label_set_text(ui_FRCScreen_LabelInfo, "Sensor must be running for min. 120sec in stable CO2 concentration");
    lv_obj_set_style_text_align(ui_FRCScreen_LabelInfo, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_FRCScreen_LabelInfo, &ui_font_Arial_Bold_13, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FRCScreen_LabelRuntime = lv_label_create(ui_FRCScreen_PanelInfo);
    lv_obj_set_width(ui_FRCScreen_LabelRuntime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FRCScreen_LabelRuntime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FRCScreen_LabelRuntime, 0);
    lv_obj_set_y(ui_FRCScreen_LabelRuntime, 70);
    lv_obj_set_align(ui_FRCScreen_LabelRuntime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_FRCScreen_LabelRuntime, ">120sec");
    ui_object_set_themeable_style_property(ui_FRCScreen_LabelRuntime, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Green);
    ui_object_set_themeable_style_property(ui_FRCScreen_LabelRuntime, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Green);
    lv_obj_set_style_text_font(ui_FRCScreen_LabelRuntime, &ui_font_Arial_Black_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_FRCScreen_LabelRuntime, LV_PART_MAIN | LV_STATE_USER_1, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Red);
    ui_object_set_themeable_style_property(ui_FRCScreen_LabelRuntime, LV_PART_MAIN | LV_STATE_USER_1, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Red);

}
