// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: IAQ_Monitor_UI

#include "ui.h"

void ui_MainScreen_screen_init(void)
{
    ui_MainScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MainScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MainScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainScreen_Container1 = lv_obj_create(ui_MainScreen);
    lv_obj_remove_style_all(ui_MainScreen_Container1);
    lv_obj_set_width(ui_MainScreen_Container1, lv_pct(100));
    lv_obj_set_height(ui_MainScreen_Container1, lv_pct(100));
    lv_obj_set_align(ui_MainScreen_Container1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_MainScreen_Container1, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_MainScreen_Container1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_END);
    lv_obj_clear_flag(ui_MainScreen_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_MainScreen_Container1, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_MainScreen_Container1, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_MainScreen_Container1, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_MainScreen_Container1, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_MainScreen_Container1, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_MainScreen_Container1, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainScreen_TilePM = ui_Tile_create(ui_MainScreen_Container1);
    lv_obj_set_x(ui_MainScreen_TilePM, 4);
    lv_obj_set_y(ui_MainScreen_TilePM, -4);

    lv_label_set_text(ui_comp_get_child(ui_MainScreen_TilePM, UI_COMP_TILE_POLUTANT), "PM2.5");

    lv_label_set_text(ui_comp_get_child(ui_MainScreen_TilePM, UI_COMP_TILE_UNIT), "ug/m3");

    ui_MainScreen_TileRH = ui_Tile_create(ui_MainScreen_Container1);
    lv_obj_set_x(ui_MainScreen_TileRH, 4);
    lv_obj_set_y(ui_MainScreen_TileRH, -4);

    lv_label_set_text(ui_comp_get_child(ui_MainScreen_TileRH, UI_COMP_TILE_VALUE), "50.0");

    lv_label_set_text(ui_comp_get_child(ui_MainScreen_TileRH, UI_COMP_TILE_POLUTANT), "RH");

    lv_label_set_text(ui_comp_get_child(ui_MainScreen_TileRH, UI_COMP_TILE_UNIT), "%");

    ui_MainScreen_TileT = ui_Tile_create(ui_MainScreen_Container1);
    lv_obj_set_x(ui_MainScreen_TileT, 4);
    lv_obj_set_y(ui_MainScreen_TileT, -4);

    lv_label_set_text(ui_comp_get_child(ui_MainScreen_TileT, UI_COMP_TILE_VALUE), "22.7");

    lv_label_set_text(ui_comp_get_child(ui_MainScreen_TileT, UI_COMP_TILE_POLUTANT), "T");

    lv_label_set_text(ui_comp_get_child(ui_MainScreen_TileT, UI_COMP_TILE_UNIT), "°C");

    ui_MainScreen_TileNOx = ui_Tile_create(ui_MainScreen_Container1);
    lv_obj_set_x(ui_MainScreen_TileNOx, 4);
    lv_obj_set_y(ui_MainScreen_TileNOx, -4);

    lv_label_set_text(ui_comp_get_child(ui_MainScreen_TileNOx, UI_COMP_TILE_VALUE), "500");

    lv_label_set_text(ui_comp_get_child(ui_MainScreen_TileNOx, UI_COMP_TILE_POLUTANT), "NOx");

    ui_MainScreen_TileVOC = ui_Tile_create(ui_MainScreen_Container1);
    lv_obj_set_x(ui_MainScreen_TileVOC, 4);
    lv_obj_set_y(ui_MainScreen_TileVOC, -4);

    lv_label_set_text(ui_comp_get_child(ui_MainScreen_TileVOC, UI_COMP_TILE_VALUE), "500");

    ui_MainScreen_TileCO2 = ui_Tile_create(ui_MainScreen_Container1);
    lv_obj_set_x(ui_MainScreen_TileCO2, 4);
    lv_obj_set_y(ui_MainScreen_TileCO2, -4);

    lv_label_set_text(ui_comp_get_child(ui_MainScreen_TileCO2, UI_COMP_TILE_VALUE), "5000");

    lv_label_set_text(ui_comp_get_child(ui_MainScreen_TileCO2, UI_COMP_TILE_POLUTANT), "CO2");

    lv_label_set_text(ui_comp_get_child(ui_MainScreen_TileCO2, UI_COMP_TILE_UNIT), "ppm");

}
