// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: IAQ_Monitor_UI

#include "ui.h"

void ui_PMScreen_screen_init(void)
{
    ui_PMScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_PMScreen, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE |
                      LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM);     /// Flags
    lv_obj_set_scrollbar_mode(ui_PMScreen, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_scroll_snap_x(ui_PMScreen, LV_SCROLL_SNAP_CENTER);
    lv_obj_set_scroll_snap_y(ui_PMScreen, LV_SCROLL_SNAP_CENTER);
    lv_obj_set_style_bg_color(ui_PMScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PMScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PMScreen_Panel1 = lv_obj_create(ui_PMScreen);
    lv_obj_set_width(ui_PMScreen_Panel1, 166);
    lv_obj_set_height(ui_PMScreen_Panel1, 310);
    lv_obj_set_align(ui_PMScreen_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PMScreen_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PMScreen_Panel1, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PMScreen_Panel1, lv_color_hex(0x182831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PMScreen_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PMScreen_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_PMScreen_Panel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PMScreen_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PMScreen_Panel1, &ui_font_Arial_Bold_13, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PMScreen_PMValues = lv_obj_create(ui_PMScreen_Panel1);
    lv_obj_remove_style_all(ui_PMScreen_PMValues);
    lv_obj_set_width(ui_PMScreen_PMValues, 150);
    lv_obj_set_height(ui_PMScreen_PMValues, 100);
    lv_obj_set_x(ui_PMScreen_PMValues, -5);
    lv_obj_set_y(ui_PMScreen_PMValues, -3);
    lv_obj_set_flex_flow(ui_PMScreen_PMValues, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_PMScreen_PMValues, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_PMScreen_PMValues, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_PMScreen_PMValues, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PMScreen_PMValues, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PMScreen_PMValues, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PMScreen_PMValues, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_PMScreen_PMValues, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_PMScreen_PMValues, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PMScreen_PMValues, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PMScreen_PMValues, &ui_font_Arial_Bold_13, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PMScreen_PM1 = lv_obj_create(ui_PMScreen_PMValues);
    lv_obj_remove_style_all(ui_PMScreen_PM1);
    lv_obj_set_width(ui_PMScreen_PM1, 67);
    lv_obj_set_height(ui_PMScreen_PM1, 40);
    lv_obj_set_align(ui_PMScreen_PM1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PMScreen_PM1, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_PMScreen_PM1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_PMScreen_PM1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_PMScreen_PM1, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_PMScreen_PM1, 6, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PMScreen_Pollutant = lv_label_create(ui_PMScreen_PM1);
    lv_obj_set_width(ui_PMScreen_Pollutant, lv_pct(100));
    lv_obj_set_height(ui_PMScreen_Pollutant, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PMScreen_Pollutant, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PMScreen_Pollutant, "PM1.0");
    lv_obj_set_style_text_color(ui_PMScreen_Pollutant, lv_color_hex(0x3981F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PMScreen_Pollutant, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PMScreen_Value = lv_label_create(ui_PMScreen_PM1);
    lv_obj_set_width(ui_PMScreen_Value, lv_pct(100));
    lv_obj_set_height(ui_PMScreen_Value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PMScreen_Value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PMScreen_Value, "100.1");
    ui_object_set_themeable_style_property(ui_PMScreen_Value, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Green);
    ui_object_set_themeable_style_property(ui_PMScreen_Value, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Green);
    lv_obj_set_style_text_font(ui_PMScreen_Value, &ui_font_Arial_Black_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PMScreen_PM25 = lv_obj_create(ui_PMScreen_PMValues);
    lv_obj_remove_style_all(ui_PMScreen_PM25);
    lv_obj_set_width(ui_PMScreen_PM25, 67);
    lv_obj_set_height(ui_PMScreen_PM25, 40);
    lv_obj_set_align(ui_PMScreen_PM25, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PMScreen_PM25, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_PMScreen_PM25, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_PMScreen_PM25, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_PMScreen_PM25, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_PMScreen_PM25, 6, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PMScreen_Pollutant1 = lv_label_create(ui_PMScreen_PM25);
    lv_obj_set_width(ui_PMScreen_Pollutant1, lv_pct(100));
    lv_obj_set_height(ui_PMScreen_Pollutant1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PMScreen_Pollutant1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PMScreen_Pollutant1, "PM2.5");
    lv_obj_set_style_text_color(ui_PMScreen_Pollutant1, lv_color_hex(0xEE489C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PMScreen_Pollutant1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PMScreen_Value1 = lv_label_create(ui_PMScreen_PM25);
    lv_obj_set_width(ui_PMScreen_Value1, lv_pct(100));
    lv_obj_set_height(ui_PMScreen_Value1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PMScreen_Value1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PMScreen_Value1, "100.1");
    ui_object_set_themeable_style_property(ui_PMScreen_Value1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Green);
    ui_object_set_themeable_style_property(ui_PMScreen_Value1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Green);
    lv_obj_set_style_text_font(ui_PMScreen_Value1, &ui_font_Arial_Black_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PMScreen_PM4 = lv_obj_create(ui_PMScreen_PMValues);
    lv_obj_remove_style_all(ui_PMScreen_PM4);
    lv_obj_set_width(ui_PMScreen_PM4, 67);
    lv_obj_set_height(ui_PMScreen_PM4, 40);
    lv_obj_set_align(ui_PMScreen_PM4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PMScreen_PM4, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_PMScreen_PM4, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_PMScreen_PM4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_PMScreen_PM4, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_PMScreen_PM4, 6, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PMScreen_Pollutant2 = lv_label_create(ui_PMScreen_PM4);
    lv_obj_set_width(ui_PMScreen_Pollutant2, lv_pct(100));
    lv_obj_set_height(ui_PMScreen_Pollutant2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PMScreen_Pollutant2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PMScreen_Pollutant2, "PM4.0");
    lv_obj_set_style_text_color(ui_PMScreen_Pollutant2, lv_color_hex(0xAC55F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PMScreen_Pollutant2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PMScreen_Value2 = lv_label_create(ui_PMScreen_PM4);
    lv_obj_set_width(ui_PMScreen_Value2, lv_pct(100));
    lv_obj_set_height(ui_PMScreen_Value2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PMScreen_Value2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PMScreen_Value2, "100.1");
    ui_object_set_themeable_style_property(ui_PMScreen_Value2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Green);
    ui_object_set_themeable_style_property(ui_PMScreen_Value2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Green);
    lv_obj_set_style_text_font(ui_PMScreen_Value2, &ui_font_Arial_Black_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PMScreen_PM10 = lv_obj_create(ui_PMScreen_PMValues);
    lv_obj_remove_style_all(ui_PMScreen_PM10);
    lv_obj_set_width(ui_PMScreen_PM10, 67);
    lv_obj_set_height(ui_PMScreen_PM10, 40);
    lv_obj_set_align(ui_PMScreen_PM10, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PMScreen_PM10, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_PMScreen_PM10, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_PMScreen_PM10, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_PMScreen_PM10, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_PMScreen_PM10, 6, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PMScreen_Pollutant3 = lv_label_create(ui_PMScreen_PM10);
    lv_obj_set_width(ui_PMScreen_Pollutant3, lv_pct(100));
    lv_obj_set_height(ui_PMScreen_Pollutant3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PMScreen_Pollutant3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PMScreen_Pollutant3, "PM10.0");
    lv_obj_set_style_text_color(ui_PMScreen_Pollutant3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PMScreen_Pollutant3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PMScreen_Value3 = lv_label_create(ui_PMScreen_PM10);
    lv_obj_set_width(ui_PMScreen_Value3, lv_pct(100));
    lv_obj_set_height(ui_PMScreen_Value3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PMScreen_Value3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PMScreen_Value3, "100.1");
    ui_object_set_themeable_style_property(ui_PMScreen_Value3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Green);
    ui_object_set_themeable_style_property(ui_PMScreen_Value3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Green);
    lv_obj_set_style_text_font(ui_PMScreen_Value3, &ui_font_Arial_Black_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PMScreen_Unit = lv_label_create(ui_PMScreen_Panel1);
    lv_obj_set_width(ui_PMScreen_Unit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PMScreen_Unit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PMScreen_Unit, 0);
    lv_obj_set_y(ui_PMScreen_Unit, -40);
    lv_obj_set_align(ui_PMScreen_Unit, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PMScreen_Unit, "µg/m3 over time");
    lv_obj_set_style_text_font(ui_PMScreen_Unit, &ui_font_Arial_Bold_13, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PMScreen_PMChart = lv_chart_create(ui_PMScreen_Panel1);
    lv_obj_set_width(ui_PMScreen_PMChart, 156);
    lv_obj_set_height(ui_PMScreen_PMChart, 155);
    lv_obj_set_x(ui_PMScreen_PMChart, 0);
    lv_obj_set_y(ui_PMScreen_PMChart, -10);
    lv_obj_set_align(ui_PMScreen_PMChart, LV_ALIGN_BOTTOM_MID);
    lv_chart_set_type(ui_PMScreen_PMChart, LV_CHART_TYPE_LINE);
    lv_chart_set_point_count(ui_PMScreen_PMChart, 150);
    lv_chart_set_range(ui_PMScreen_PMChart, LV_CHART_AXIS_PRIMARY_Y, 0, 10);
    lv_chart_set_div_line_count(ui_PMScreen_PMChart, 0, 0);
    lv_chart_set_axis_tick(ui_PMScreen_PMChart, LV_CHART_AXIS_PRIMARY_X, 5, 0, 3, 0, false, 13);
    lv_chart_set_axis_tick(ui_PMScreen_PMChart, LV_CHART_AXIS_PRIMARY_Y, 0, 0, 5, 2, false, 50);
    lv_chart_set_axis_tick(ui_PMScreen_PMChart, LV_CHART_AXIS_SECONDARY_Y, 0, 0, 5, 2, false, 25);
    lv_obj_set_style_bg_color(ui_PMScreen_PMChart, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PMScreen_PMChart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PMScreen_PMChart, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_size(ui_PMScreen_PMChart, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_PMScreen_PMChart, lv_color_hex(0xFFFFFF), LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PMScreen_PMChart, 255, LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PMScreen_PMChart, &ui_font_Arial_Bold_13, LV_PART_TICKS | LV_STATE_DEFAULT);

    ui_PMScreen_XMinValue = lv_label_create(ui_PMScreen_Panel1);
    lv_obj_set_width(ui_PMScreen_XMinValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PMScreen_XMinValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PMScreen_XMinValue, -5);
    lv_obj_set_y(ui_PMScreen_XMinValue, 8);
    lv_obj_set_align(ui_PMScreen_XMinValue, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_PMScreen_XMinValue, "-2min30");

    ui_PMScreen_XMaxValue = lv_label_create(ui_PMScreen_Panel1);
    lv_obj_set_width(ui_PMScreen_XMaxValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PMScreen_XMaxValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PMScreen_XMaxValue, 5);
    lv_obj_set_y(ui_PMScreen_XMaxValue, 8);
    lv_obj_set_align(ui_PMScreen_XMaxValue, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_PMScreen_XMaxValue, "0");

    ui_PMScreen_YMinValue = lv_label_create(ui_PMScreen_Panel1);
    lv_obj_set_width(ui_PMScreen_YMinValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PMScreen_YMinValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PMScreen_YMinValue, -5);
    lv_obj_set_y(ui_PMScreen_YMinValue, -10);
    lv_obj_set_align(ui_PMScreen_YMinValue, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_PMScreen_YMinValue, "0");
    lv_obj_set_style_text_font(ui_PMScreen_YMinValue, &ui_font_Arial_Bold_13, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PMScreen_YMaxValue = lv_label_create(ui_PMScreen_Panel1);
    lv_obj_set_width(ui_PMScreen_YMaxValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PMScreen_YMaxValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PMScreen_YMaxValue, -5);
    lv_obj_set_y(ui_PMScreen_YMaxValue, -149);
    lv_obj_set_align(ui_PMScreen_YMaxValue, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_PMScreen_YMaxValue, "10");
    lv_label_set_recolor(ui_PMScreen_YMaxValue, "true");
    lv_obj_set_style_text_font(ui_PMScreen_YMaxValue, &ui_font_Arial_Bold_13, LV_PART_MAIN | LV_STATE_DEFAULT);

}
