// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: IAQ_Monitor_UI

#include "ui.h"

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Screen2_Image12 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_Screen2_Image12, &ui_img_pmscreen_png);
    lv_obj_set_width(ui_Screen2_Image12, LV_SIZE_CONTENT);   /// 167
    lv_obj_set_height(ui_Screen2_Image12, LV_SIZE_CONTENT);    /// 316
    lv_obj_set_align(ui_Screen2_Image12, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen2_Image12, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Screen2_Image12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}
