// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: IAQ_Monitor_UI

#include "ui.h"

void ui_SettingsScreen_screen_init(void)
{
    ui_SettingsScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SettingsScreen,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM);     /// Flags
    lv_obj_set_scrollbar_mode(ui_SettingsScreen, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_scroll_snap_x(ui_SettingsScreen, LV_SCROLL_SNAP_CENTER);
    lv_obj_set_scroll_snap_y(ui_SettingsScreen, LV_SCROLL_SNAP_CENTER);
    lv_obj_set_style_bg_color(ui_SettingsScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SettingsScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingsScreen_Panel = lv_obj_create(ui_SettingsScreen);
    lv_obj_set_width(ui_SettingsScreen_Panel, 166);
    lv_obj_set_height(ui_SettingsScreen_Panel, 310);
    lv_obj_set_align(ui_SettingsScreen_Panel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SettingsScreen_Panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SettingsScreen_Panel, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SettingsScreen_Panel, lv_color_hex(0x182831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SettingsScreen_Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SettingsScreen_Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_SettingsScreen_Panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SettingsScreen_Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SettingsScreen_Panel, &ui_font_Arial_Bold_13, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingsScreen_Pollutant = lv_label_create(ui_SettingsScreen_Panel);
    lv_obj_set_width(ui_SettingsScreen_Pollutant, lv_pct(100));
    lv_obj_set_height(ui_SettingsScreen_Pollutant, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SettingsScreen_Pollutant, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_SettingsScreen_Pollutant, "Settings");
    lv_obj_set_style_text_align(ui_SettingsScreen_Pollutant, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SettingsScreen_Pollutant, &ui_font_Arial_Black_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingsScreen_Symbol = lv_img_create(ui_SettingsScreen_Panel);
    lv_img_set_src(ui_SettingsScreen_Symbol, &ui_img_cog_png);
    lv_obj_set_width(ui_SettingsScreen_Symbol, 48);
    lv_obj_set_height(ui_SettingsScreen_Symbol, 48);
    lv_obj_set_align(ui_SettingsScreen_Symbol, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SettingsScreen_Symbol, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SettingsScreen_Symbol, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SettingsScreen_Container = lv_obj_create(ui_SettingsScreen_Panel);
    lv_obj_remove_style_all(ui_SettingsScreen_Container);
    lv_obj_set_width(ui_SettingsScreen_Container, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SettingsScreen_Container, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SettingsScreen_Container, 9);
    lv_obj_set_y(ui_SettingsScreen_Container, 7);
    lv_obj_set_align(ui_SettingsScreen_Container, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_set_flex_flow(ui_SettingsScreen_Container, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_SettingsScreen_Container, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_SettingsScreen_Container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SettingsScreen_Label = lv_label_create(ui_SettingsScreen_Container);
    lv_obj_set_width(ui_SettingsScreen_Label, 86);
    lv_obj_set_height(ui_SettingsScreen_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SettingsScreen_Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SettingsScreen_Label, "long press to enter settings");
    lv_obj_set_style_text_align(ui_SettingsScreen_Label, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SettingsScreen_Label, &ui_font_Arial_Bold_13, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingsScreen_Image = lv_img_create(ui_SettingsScreen_Container);
    lv_img_set_src(ui_SettingsScreen_Image, &ui_img_718623388);
    lv_obj_set_width(ui_SettingsScreen_Image, 28);
    lv_obj_set_height(ui_SettingsScreen_Image, 28);
    lv_obj_set_align(ui_SettingsScreen_Image, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SettingsScreen_Image, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SettingsScreen_Image, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}
