// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: IAQ_Monitor_UI

#include "ui.h"

void ui_TempScreen_screen_init(void)
{
    ui_TempScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_TempScreen, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE |
                      LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM);     /// Flags
    lv_obj_set_scrollbar_mode(ui_TempScreen, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_scroll_snap_x(ui_TempScreen, LV_SCROLL_SNAP_CENTER);
    lv_obj_set_scroll_snap_y(ui_TempScreen, LV_SCROLL_SNAP_CENTER);
    lv_obj_set_style_bg_color(ui_TempScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TempScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempScreen_Panel = lv_obj_create(ui_TempScreen);
    lv_obj_set_width(ui_TempScreen_Panel, 166);
    lv_obj_set_height(ui_TempScreen_Panel, 310);
    lv_obj_set_align(ui_TempScreen_Panel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TempScreen_Panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_TempScreen_Panel, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TempScreen_Panel, lv_color_hex(0x182831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TempScreen_Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_TempScreen_Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_TempScreen_Panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TempScreen_Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TempScreen_Panel, &ui_font_Arial_Bold_13, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempScreen_Container = lv_obj_create(ui_TempScreen_Panel);
    lv_obj_remove_style_all(ui_TempScreen_Container);
    lv_obj_set_height(ui_TempScreen_Container, 100);
    lv_obj_set_width(ui_TempScreen_Container, lv_pct(100));
    lv_obj_set_flex_flow(ui_TempScreen_Container, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_TempScreen_Container, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_TempScreen_Container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_TempScreen_Container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_TempScreen_Container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_TempScreen_Container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_TempScreen_Container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_TempScreen_Container, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_TempScreen_Container, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_TempScreen_Container, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TempScreen_Container, &ui_font_Arial_Bold_13, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempScreen_Title = lv_obj_create(ui_TempScreen_Container);
    lv_obj_remove_style_all(ui_TempScreen_Title);
    lv_obj_set_width(ui_TempScreen_Title, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TempScreen_Title, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TempScreen_Title, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_TempScreen_Title, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_TempScreen_Title, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_TempScreen_Title, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_TempScreen_Title, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_TempScreen_Title, 6, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempScreen_Symbol = lv_img_create(ui_TempScreen_Title);
    lv_img_set_src(ui_TempScreen_Symbol, &ui_img_thermometer_white_png);
    lv_obj_set_width(ui_TempScreen_Symbol, 20);
    lv_obj_set_height(ui_TempScreen_Symbol, 20);
    lv_obj_set_align(ui_TempScreen_Symbol, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TempScreen_Symbol, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_TempScreen_Symbol, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TempScreen_Pollutant = lv_label_create(ui_TempScreen_Title);
    lv_obj_set_width(ui_TempScreen_Pollutant, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TempScreen_Pollutant, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TempScreen_Pollutant, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TempScreen_Pollutant, "Temperature");

    ui_TempScreen_Value = lv_label_create(ui_TempScreen_Container);
    lv_obj_set_width(ui_TempScreen_Value, lv_pct(100));
    lv_obj_set_height(ui_TempScreen_Value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TempScreen_Value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TempScreen_Value, "25.3");
    ui_object_set_themeable_style_property(ui_TempScreen_Value, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Green);
    ui_object_set_themeable_style_property(ui_TempScreen_Value, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Green);
    lv_obj_set_style_text_font(ui_TempScreen_Value, &ui_font_Arial_Black_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempScreen_Unit = lv_label_create(ui_TempScreen_Container);
    lv_obj_set_width(ui_TempScreen_Unit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TempScreen_Unit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TempScreen_Unit, 0);
    lv_obj_set_y(ui_TempScreen_Unit, -75);
    lv_obj_set_align(ui_TempScreen_Unit, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TempScreen_Unit, "°C over time");
    lv_obj_set_style_text_font(ui_TempScreen_Unit, &ui_font_Arial_Bold_13, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempScreen_TempChart = lv_chart_create(ui_TempScreen_Panel);
    lv_obj_set_width(ui_TempScreen_TempChart, 156);
    lv_obj_set_height(ui_TempScreen_TempChart, 185);
    lv_obj_set_x(ui_TempScreen_TempChart, 0);
    lv_obj_set_y(ui_TempScreen_TempChart, -10);
    lv_obj_set_align(ui_TempScreen_TempChart, LV_ALIGN_BOTTOM_MID);
    lv_chart_set_type(ui_TempScreen_TempChart, LV_CHART_TYPE_LINE);
    lv_chart_set_point_count(ui_TempScreen_TempChart, 150);
    lv_chart_set_range(ui_TempScreen_TempChart, LV_CHART_AXIS_PRIMARY_Y, 15, 35);
    lv_chart_set_div_line_count(ui_TempScreen_TempChart, 0, 0);
    lv_chart_set_axis_tick(ui_TempScreen_TempChart, LV_CHART_AXIS_PRIMARY_X, 5, 0, 3, 0, false, 13);
    lv_chart_set_axis_tick(ui_TempScreen_TempChart, LV_CHART_AXIS_PRIMARY_Y, 0, 0, 5, 2, false, 50);
    lv_chart_set_axis_tick(ui_TempScreen_TempChart, LV_CHART_AXIS_SECONDARY_Y, 0, 0, 5, 2, false, 25);
    lv_obj_set_style_bg_color(ui_TempScreen_TempChart, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TempScreen_TempChart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_TempScreen_TempChart, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_size(ui_TempScreen_TempChart, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_TempScreen_TempChart, lv_color_hex(0xFFFFFF), LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TempScreen_TempChart, 255, LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TempScreen_TempChart, &ui_font_Arial_Bold_13, LV_PART_TICKS | LV_STATE_DEFAULT);

    ui_TempScreen_XMinValue = lv_label_create(ui_TempScreen_Panel);
    lv_obj_set_width(ui_TempScreen_XMinValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TempScreen_XMinValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TempScreen_XMinValue, -5);
    lv_obj_set_y(ui_TempScreen_XMinValue, 8);
    lv_obj_set_align(ui_TempScreen_XMinValue, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_TempScreen_XMinValue, "-2min30");

    ui_TempScreen_XMaxValue = lv_label_create(ui_TempScreen_Panel);
    lv_obj_set_width(ui_TempScreen_XMaxValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TempScreen_XMaxValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TempScreen_XMaxValue, 5);
    lv_obj_set_y(ui_TempScreen_XMaxValue, 8);
    lv_obj_set_align(ui_TempScreen_XMaxValue, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_TempScreen_XMaxValue, "0");

    ui_TempScreen_YMinValue = lv_label_create(ui_TempScreen_Panel);
    lv_obj_set_width(ui_TempScreen_YMinValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TempScreen_YMinValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TempScreen_YMinValue, -5);
    lv_obj_set_y(ui_TempScreen_YMinValue, -10);
    lv_obj_set_align(ui_TempScreen_YMinValue, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_TempScreen_YMinValue, "15");
    lv_obj_set_style_text_font(ui_TempScreen_YMinValue, &ui_font_Arial_Bold_13, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempScreen_YMaxValue = lv_label_create(ui_TempScreen_Panel);
    lv_obj_set_width(ui_TempScreen_YMaxValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TempScreen_YMaxValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TempScreen_YMaxValue, -5);
    lv_obj_set_y(ui_TempScreen_YMaxValue, -178);
    lv_obj_set_align(ui_TempScreen_YMaxValue, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_TempScreen_YMaxValue, "35");
    lv_label_set_recolor(ui_TempScreen_YMaxValue, "true");
    lv_obj_set_style_text_font(ui_TempScreen_YMaxValue, &ui_font_Arial_Bold_13, LV_PART_MAIN | LV_STATE_DEFAULT);

}
