// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: IAQ_Monitor_UI

#include "ui.h"

void ui_VOCScreen_screen_init(void)
{
    ui_VOCScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_VOCScreen, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE |
                      LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM);     /// Flags
    lv_obj_set_scrollbar_mode(ui_VOCScreen, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_scroll_snap_x(ui_VOCScreen, LV_SCROLL_SNAP_CENTER);
    lv_obj_set_scroll_snap_y(ui_VOCScreen, LV_SCROLL_SNAP_CENTER);
    lv_obj_set_style_bg_color(ui_VOCScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_VOCScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VOCScreen_Panel = lv_obj_create(ui_VOCScreen);
    lv_obj_set_width(ui_VOCScreen_Panel, 166);
    lv_obj_set_height(ui_VOCScreen_Panel, 310);
    lv_obj_set_align(ui_VOCScreen_Panel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_VOCScreen_Panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_VOCScreen_Panel, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_VOCScreen_Panel, lv_color_hex(0x182831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_VOCScreen_Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_VOCScreen_Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_VOCScreen_Panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VOCScreen_Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_VOCScreen_Panel, &ui_font_Arial_Bold_13, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VOCScreen_Container = lv_obj_create(ui_VOCScreen_Panel);
    lv_obj_remove_style_all(ui_VOCScreen_Container);
    lv_obj_set_height(ui_VOCScreen_Container, 100);
    lv_obj_set_width(ui_VOCScreen_Container, lv_pct(100));
    lv_obj_set_flex_flow(ui_VOCScreen_Container, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_VOCScreen_Container, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_VOCScreen_Container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_VOCScreen_Container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_VOCScreen_Container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_VOCScreen_Container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_VOCScreen_Container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_VOCScreen_Container, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_VOCScreen_Container, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_VOCScreen_Container, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_VOCScreen_Container, &ui_font_Arial_Bold_13, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VOCScreen_Title = lv_obj_create(ui_VOCScreen_Container);
    lv_obj_remove_style_all(ui_VOCScreen_Title);
    lv_obj_set_width(ui_VOCScreen_Title, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VOCScreen_Title, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_VOCScreen_Title, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_VOCScreen_Title, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_VOCScreen_Title, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_VOCScreen_Title, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_VOCScreen_Title, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_VOCScreen_Title, 6, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VOCScreen_Symbol = lv_img_create(ui_VOCScreen_Title);
    lv_img_set_src(ui_VOCScreen_Symbol, &ui_img_417669948);
    lv_obj_set_width(ui_VOCScreen_Symbol, 20);
    lv_obj_set_height(ui_VOCScreen_Symbol, 20);
    lv_obj_set_align(ui_VOCScreen_Symbol, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_VOCScreen_Symbol, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_VOCScreen_Symbol, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_VOCScreen_Pollutant = lv_label_create(ui_VOCScreen_Title);
    lv_obj_set_width(ui_VOCScreen_Pollutant, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VOCScreen_Pollutant, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_VOCScreen_Pollutant, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VOCScreen_Pollutant, "VOC");

    ui_VOCScreen_Value = lv_label_create(ui_VOCScreen_Container);
    lv_obj_set_width(ui_VOCScreen_Value, lv_pct(100));
    lv_obj_set_height(ui_VOCScreen_Value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_VOCScreen_Value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VOCScreen_Value, "100");
    ui_object_set_themeable_style_property(ui_VOCScreen_Value, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Green);
    ui_object_set_themeable_style_property(ui_VOCScreen_Value, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Green);
    lv_obj_set_style_text_font(ui_VOCScreen_Value, &ui_font_Arial_Black_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VOCScreen_Unit = lv_label_create(ui_VOCScreen_Container);
    lv_obj_set_width(ui_VOCScreen_Unit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VOCScreen_Unit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VOCScreen_Unit, 0);
    lv_obj_set_y(ui_VOCScreen_Unit, -75);
    lv_obj_set_align(ui_VOCScreen_Unit, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VOCScreen_Unit, "index points over time");
    lv_obj_set_style_text_font(ui_VOCScreen_Unit, &ui_font_Arial_Bold_13, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VOCScreen_VOCChart = lv_chart_create(ui_VOCScreen_Panel);
    lv_obj_set_width(ui_VOCScreen_VOCChart, 156);
    lv_obj_set_height(ui_VOCScreen_VOCChart, 185);
    lv_obj_set_x(ui_VOCScreen_VOCChart, 0);
    lv_obj_set_y(ui_VOCScreen_VOCChart, -10);
    lv_obj_set_align(ui_VOCScreen_VOCChart, LV_ALIGN_BOTTOM_MID);
    lv_chart_set_type(ui_VOCScreen_VOCChart, LV_CHART_TYPE_LINE);
    lv_chart_set_point_count(ui_VOCScreen_VOCChart, 150);
    lv_chart_set_range(ui_VOCScreen_VOCChart, LV_CHART_AXIS_PRIMARY_Y, 0, 500);
    lv_chart_set_div_line_count(ui_VOCScreen_VOCChart, 0, 0);
    lv_chart_set_axis_tick(ui_VOCScreen_VOCChart, LV_CHART_AXIS_PRIMARY_X, 5, 0, 3, 0, false, 13);
    lv_chart_set_axis_tick(ui_VOCScreen_VOCChart, LV_CHART_AXIS_PRIMARY_Y, 0, 0, 5, 2, false, 50);
    lv_chart_set_axis_tick(ui_VOCScreen_VOCChart, LV_CHART_AXIS_SECONDARY_Y, 0, 0, 5, 2, false, 25);
    lv_obj_set_style_bg_color(ui_VOCScreen_VOCChart, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_VOCScreen_VOCChart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_VOCScreen_VOCChart, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_size(ui_VOCScreen_VOCChart, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_VOCScreen_VOCChart, lv_color_hex(0xFFFFFF), LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VOCScreen_VOCChart, 255, LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_VOCScreen_VOCChart, &ui_font_Arial_Bold_13, LV_PART_TICKS | LV_STATE_DEFAULT);

    ui_VOCScreen_XMinValue = lv_label_create(ui_VOCScreen_Panel);
    lv_obj_set_width(ui_VOCScreen_XMinValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VOCScreen_XMinValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VOCScreen_XMinValue, -5);
    lv_obj_set_y(ui_VOCScreen_XMinValue, 8);
    lv_obj_set_align(ui_VOCScreen_XMinValue, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_VOCScreen_XMinValue, "-2min30");

    ui_VOCScreen_XMaxValue = lv_label_create(ui_VOCScreen_Panel);
    lv_obj_set_width(ui_VOCScreen_XMaxValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VOCScreen_XMaxValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VOCScreen_XMaxValue, 5);
    lv_obj_set_y(ui_VOCScreen_XMaxValue, 8);
    lv_obj_set_align(ui_VOCScreen_XMaxValue, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_VOCScreen_XMaxValue, "0");

    ui_VOCScreen_YMinValue = lv_label_create(ui_VOCScreen_Panel);
    lv_obj_set_width(ui_VOCScreen_YMinValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VOCScreen_YMinValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VOCScreen_YMinValue, -5);
    lv_obj_set_y(ui_VOCScreen_YMinValue, -10);
    lv_obj_set_align(ui_VOCScreen_YMinValue, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_VOCScreen_YMinValue, "0");
    lv_obj_set_style_text_font(ui_VOCScreen_YMinValue, &ui_font_Arial_Bold_13, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VOCScreen_YMaxValue = lv_label_create(ui_VOCScreen_Panel);
    lv_obj_set_width(ui_VOCScreen_YMaxValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VOCScreen_YMaxValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VOCScreen_YMaxValue, -5);
    lv_obj_set_y(ui_VOCScreen_YMaxValue, -178);
    lv_obj_set_align(ui_VOCScreen_YMaxValue, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_VOCScreen_YMaxValue, "500");
    lv_label_set_recolor(ui_VOCScreen_YMaxValue, "true");
    lv_obj_set_style_text_font(ui_VOCScreen_YMaxValue, &ui_font_Arial_Bold_13, LV_PART_MAIN | LV_STATE_DEFAULT);

}
