// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: Settings

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_FRCScreen
void ui_FRCScreen_screen_init(void);
lv_obj_t * ui_FRCScreen;
lv_obj_t * ui_FRCScreen_Container;
lv_obj_t * ui_FRCScreen_ContainerUp;
lv_obj_t * ui_FRCScreen_LabelUp;
lv_obj_t * ui_FRCScreen_ImageUp;
lv_obj_t * ui_FRCScreen_Panel;
lv_obj_t * ui_FRCScreen_Title;
lv_obj_t * ui_FRCScreen_TargetValue;
lv_obj_t * ui_FRCScreen_Unit;
lv_obj_t * ui_FRCScreen_ContainerDown;
lv_obj_t * ui_FRCScreen_ImageDown;
lv_obj_t * ui_FRCScreen_LabelDown;
lv_obj_t * ui_FRCScreen_ContainerRight;
lv_obj_t * ui_FRCScreen_LabelRight;
lv_obj_t * ui_FRCScreen_ImageRight;
lv_obj_t * ui_FRCScreen_ContainerLeft;
lv_obj_t * ui_FRCScreen_ImageLeft;
lv_obj_t * ui_FRCScreen_LabelLeft;
lv_obj_t * ui_FRCScreen_PanelInfo;
lv_obj_t * ui_FRCScreen_LabelInfo;
lv_obj_t * ui_FRCScreen_LabelRuntime;
// CUSTOM VARIABLES

// SCREEN: ui_AltitudeScreen
void ui_AltitudeScreen_screen_init(void);
lv_obj_t * ui_AltitudeScreen;
lv_obj_t * ui_AltitudeScreen_Container;
lv_obj_t * ui_AltitudeScreen_ContainerUp;
lv_obj_t * ui_AltitudeScreen_LabelUp;
lv_obj_t * ui_AltitudeScreen_ImageUp;
lv_obj_t * ui_AltitudeScreen_Panel;
lv_obj_t * ui_AltitudeScreen_Title;
lv_obj_t * ui_AltitudeScreen_TargetValue;
lv_obj_t * ui_AltitudeScreen_Unit;
lv_obj_t * ui_AltitudeScreen_ContainerDown;
lv_obj_t * ui_AltitudeScreen_ImageDown;
lv_obj_t * ui_AltitudeScreen_LabelDown;
lv_obj_t * ui_AltitudeScreen_ContainerRight;
lv_obj_t * ui_AltitudeScreen_LabelRight;
lv_obj_t * ui_AltitudeScreen_ImageRight;
lv_obj_t * ui_AltitudeScreen_ContainerLeft;
lv_obj_t * ui_AltitudeScreen_ImageLeft;
lv_obj_t * ui_AltitudeScreen_LabelLeft;
// CUSTOM VARIABLES

// SCREEN: ui_ChartTimeScreen
void ui_ChartTimeScreen_screen_init(void);
lv_obj_t * ui_ChartTimeScreen;
lv_obj_t * ui_ChartTimeScreen_Container;
lv_obj_t * ui_ChartTimeScreen_ContainerUp;
lv_obj_t * ui_ChartTimeScreen_ImageUp;
lv_obj_t * ui_ChartTimeScreen_Panel;
lv_obj_t * ui_ChartTimeScreen_Title;
lv_obj_t * ui_ChartTimeScreen_CheckboxShort;
lv_obj_t * ui_ChartTimeScreen_CheckboxMedium;
lv_obj_t * ui_ChartTimeScreen_CheckboxLong;
lv_obj_t * ui_ChartTimeScreen_ContainerDown;
lv_obj_t * ui_ChartTimeScreen_ImageDown;
lv_obj_t * ui_ChartTimeScreen_ContainerRight;
lv_obj_t * ui_ChartTimeScreen_LabelRight;
lv_obj_t * ui_ChartTimeScreen_ImageRight;
lv_obj_t * ui_ChartTimeScreen_ContainerLeft;
lv_obj_t * ui_ChartTimeScreen_ImageLeft;
lv_obj_t * ui_ChartTimeScreen_LabelLeft;
lv_obj_t * ui_ChartTimeScreen_PanelInfo2;
lv_obj_t * ui_ChartTimeScreen_LabelInfo2;
// CUSTOM VARIABLES

// SCREEN: ui_BrightnessScreen
void ui_BrightnessScreen_screen_init(void);
lv_obj_t * ui_BrightnessScreen;
lv_obj_t * ui_BrightnessScreen_Container;
lv_obj_t * ui_BrightnessScreen_ContainerUp;
lv_obj_t * ui_BrightnessScreen_ImageUp;
lv_obj_t * ui_BrightnessScreen_Panel;
lv_obj_t * ui_BrightnessScreen_Title;
lv_obj_t * ui_BrightnessScreen_Checkbox100;
lv_obj_t * ui_BrightnessScreen_Checkbox75;
lv_obj_t * ui_BrightnessScreen_Checkbox50;
lv_obj_t * ui_BrightnessScreen_Checkbox25;
lv_obj_t * ui_BrightnessScreen_ContainerDown;
lv_obj_t * ui_BrightnessScreen_ImageDown;
lv_obj_t * ui_BrightnessScreen_ContainerRight;
lv_obj_t * ui_BrightnessScreen_LabelRight;
lv_obj_t * ui_BrightnessScreen_ImageRight;
lv_obj_t * ui_BrightnessScreen_ContainerLeft;
lv_obj_t * ui_BrightnessScreen_ImageLeft;
lv_obj_t * ui_BrightnessScreen_LabelLeft;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_FRCScreen_screen_init();
    ui_AltitudeScreen_screen_init();
    ui_ChartTimeScreen_screen_init();
    ui_BrightnessScreen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_FRCScreen);
}
