// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: Settings

#include "ui.h"

void ui_AltitudeScreen_screen_init(void)
{
    ui_AltitudeScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_AltitudeScreen,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM);     /// Flags
    lv_obj_set_scrollbar_mode(ui_AltitudeScreen, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_scroll_snap_x(ui_AltitudeScreen, LV_SCROLL_SNAP_CENTER);
    lv_obj_set_scroll_snap_y(ui_AltitudeScreen, LV_SCROLL_SNAP_CENTER);
    lv_obj_set_style_bg_color(ui_AltitudeScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AltitudeScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_AltitudeScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_AltitudeScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_AltitudeScreen, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_AltitudeScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AltitudeScreen_Container = lv_obj_create(ui_AltitudeScreen);
    lv_obj_remove_style_all(ui_AltitudeScreen_Container);
    lv_obj_set_width(ui_AltitudeScreen_Container, lv_pct(100));
    lv_obj_set_height(ui_AltitudeScreen_Container, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_AltitudeScreen_Container, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_AltitudeScreen_Container, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_AltitudeScreen_Container, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_AltitudeScreen_Container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AltitudeScreen_ContainerUp = lv_obj_create(ui_AltitudeScreen_Container);
    lv_obj_remove_style_all(ui_AltitudeScreen_ContainerUp);
    lv_obj_set_width(ui_AltitudeScreen_ContainerUp, 160);
    lv_obj_set_height(ui_AltitudeScreen_ContainerUp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AltitudeScreen_ContainerUp, 23);
    lv_obj_set_y(ui_AltitudeScreen_ContainerUp, -106);
    lv_obj_set_align(ui_AltitudeScreen_ContainerUp, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_AltitudeScreen_ContainerUp, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_AltitudeScreen_ContainerUp, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_AltitudeScreen_ContainerUp, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_AltitudeScreen_ContainerUp, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_AltitudeScreen_ContainerUp, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_AltitudeScreen_ContainerUp, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_AltitudeScreen_ContainerUp, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_AltitudeScreen_ContainerUp, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_AltitudeScreen_ContainerUp, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AltitudeScreen_ContainerUp, &ui_font_Arial_Bold_13, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AltitudeScreen_LabelUp = lv_label_create(ui_AltitudeScreen_ContainerUp);
    lv_obj_set_width(ui_AltitudeScreen_LabelUp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AltitudeScreen_LabelUp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_AltitudeScreen_LabelUp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AltitudeScreen_LabelUp, "+25m");

    ui_AltitudeScreen_ImageUp = lv_img_create(ui_AltitudeScreen_ContainerUp);
    lv_img_set_src(ui_AltitudeScreen_ImageUp, &ui_img_816914973);
    lv_obj_set_width(ui_AltitudeScreen_ImageUp, 20);
    lv_obj_set_height(ui_AltitudeScreen_ImageUp, 20);
    lv_obj_set_align(ui_AltitudeScreen_ImageUp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AltitudeScreen_ImageUp, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_AltitudeScreen_ImageUp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AltitudeScreen_Panel = lv_obj_create(ui_AltitudeScreen_Container);
    lv_obj_set_width(ui_AltitudeScreen_Panel, 166);
    lv_obj_set_height(ui_AltitudeScreen_Panel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_AltitudeScreen_Panel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_AltitudeScreen_Panel, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_AltitudeScreen_Panel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_AltitudeScreen_Panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_AltitudeScreen_Panel, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_AltitudeScreen_Panel, lv_color_hex(0x182831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AltitudeScreen_Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_AltitudeScreen_Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_AltitudeScreen_Panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AltitudeScreen_Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AltitudeScreen_Panel, &ui_font_Arial_Bold_13, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AltitudeScreen_Title = lv_label_create(ui_AltitudeScreen_Panel);
    lv_obj_set_width(ui_AltitudeScreen_Title, lv_pct(100));
    lv_obj_set_height(ui_AltitudeScreen_Title, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_AltitudeScreen_Title, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AltitudeScreen_Title, "Alitutde over sea level for CO2 sensor compensation");
    lv_obj_set_style_text_align(ui_AltitudeScreen_Title, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AltitudeScreen_TargetValue = lv_label_create(ui_AltitudeScreen_Panel);
    lv_obj_set_width(ui_AltitudeScreen_TargetValue, lv_pct(100));
    lv_obj_set_height(ui_AltitudeScreen_TargetValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AltitudeScreen_TargetValue, -2);
    lv_obj_set_y(ui_AltitudeScreen_TargetValue, 0);
    lv_obj_set_align(ui_AltitudeScreen_TargetValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AltitudeScreen_TargetValue, "0");
    lv_obj_set_style_text_color(ui_AltitudeScreen_TargetValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AltitudeScreen_TargetValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_AltitudeScreen_TargetValue, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AltitudeScreen_TargetValue, &ui_font_Arial_Black_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AltitudeScreen_Unit = lv_label_create(ui_AltitudeScreen_Panel);
    lv_obj_set_width(ui_AltitudeScreen_Unit, lv_pct(100));
    lv_obj_set_height(ui_AltitudeScreen_Unit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_AltitudeScreen_Unit, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AltitudeScreen_Unit, "meters above sea level");
    lv_obj_set_style_text_align(ui_AltitudeScreen_Unit, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AltitudeScreen_ContainerDown = lv_obj_create(ui_AltitudeScreen_Container);
    lv_obj_remove_style_all(ui_AltitudeScreen_ContainerDown);
    lv_obj_set_width(ui_AltitudeScreen_ContainerDown, lv_pct(100));
    lv_obj_set_height(ui_AltitudeScreen_ContainerDown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AltitudeScreen_ContainerDown, 23);
    lv_obj_set_y(ui_AltitudeScreen_ContainerDown, -106);
    lv_obj_set_align(ui_AltitudeScreen_ContainerDown, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_AltitudeScreen_ContainerDown, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_AltitudeScreen_ContainerDown, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_AltitudeScreen_ContainerDown, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_AltitudeScreen_ContainerDown, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_AltitudeScreen_ContainerDown, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_AltitudeScreen_ContainerDown, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_AltitudeScreen_ContainerDown, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_AltitudeScreen_ContainerDown, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_AltitudeScreen_ContainerDown, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AltitudeScreen_ContainerDown, &ui_font_Arial_Bold_13, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AltitudeScreen_ImageDown = lv_img_create(ui_AltitudeScreen_ContainerDown);
    lv_img_set_src(ui_AltitudeScreen_ImageDown, &ui_img_810620936);
    lv_obj_set_width(ui_AltitudeScreen_ImageDown, 20);
    lv_obj_set_height(ui_AltitudeScreen_ImageDown, 20);
    lv_obj_set_align(ui_AltitudeScreen_ImageDown, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AltitudeScreen_ImageDown, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_AltitudeScreen_ImageDown, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AltitudeScreen_LabelDown = lv_label_create(ui_AltitudeScreen_ContainerDown);
    lv_obj_set_width(ui_AltitudeScreen_LabelDown, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AltitudeScreen_LabelDown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_AltitudeScreen_LabelDown, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AltitudeScreen_LabelDown, "-25m");

    ui_AltitudeScreen_ContainerRight = lv_obj_create(ui_AltitudeScreen);
    lv_obj_remove_style_all(ui_AltitudeScreen_ContainerRight);
    lv_obj_set_width(ui_AltitudeScreen_ContainerRight, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AltitudeScreen_ContainerRight, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AltitudeScreen_ContainerRight, -5);
    lv_obj_set_y(ui_AltitudeScreen_ContainerRight, -5);
    lv_obj_set_align(ui_AltitudeScreen_ContainerRight, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_set_flex_flow(ui_AltitudeScreen_ContainerRight, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_AltitudeScreen_ContainerRight, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_AltitudeScreen_ContainerRight, LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags
    lv_obj_clear_flag(ui_AltitudeScreen_ContainerRight, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AltitudeScreen_LabelRight = lv_label_create(ui_AltitudeScreen_ContainerRight);
    lv_obj_set_width(ui_AltitudeScreen_LabelRight, 86);
    lv_obj_set_height(ui_AltitudeScreen_LabelRight, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_AltitudeScreen_LabelRight, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AltitudeScreen_LabelRight, "long press to adjust value");
    lv_obj_set_style_text_align(ui_AltitudeScreen_LabelRight, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AltitudeScreen_LabelRight, &ui_font_Arial_Bold_13, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AltitudeScreen_ImageRight = lv_img_create(ui_AltitudeScreen_ContainerRight);
    lv_img_set_src(ui_AltitudeScreen_ImageRight, &ui_img_718623388);
    lv_obj_set_width(ui_AltitudeScreen_ImageRight, 28);
    lv_obj_set_height(ui_AltitudeScreen_ImageRight, 28);
    lv_obj_set_align(ui_AltitudeScreen_ImageRight, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AltitudeScreen_ImageRight, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_AltitudeScreen_ImageRight, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AltitudeScreen_ContainerLeft = lv_obj_create(ui_AltitudeScreen);
    lv_obj_remove_style_all(ui_AltitudeScreen_ContainerLeft);
    lv_obj_set_width(ui_AltitudeScreen_ContainerLeft, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AltitudeScreen_ContainerLeft, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AltitudeScreen_ContainerLeft, 5);
    lv_obj_set_y(ui_AltitudeScreen_ContainerLeft, -40);
    lv_obj_set_align(ui_AltitudeScreen_ContainerLeft, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_set_flex_flow(ui_AltitudeScreen_ContainerLeft, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_AltitudeScreen_ContainerLeft, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_AltitudeScreen_ContainerLeft, LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags
    lv_obj_clear_flag(ui_AltitudeScreen_ContainerLeft, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_AltitudeScreen_ContainerLeft, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_AltitudeScreen_ContainerLeft, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AltitudeScreen_ImageLeft = lv_img_create(ui_AltitudeScreen_ContainerLeft);
    lv_img_set_src(ui_AltitudeScreen_ImageLeft, &ui_img_1346862293);
    lv_obj_set_width(ui_AltitudeScreen_ImageLeft, 28);
    lv_obj_set_height(ui_AltitudeScreen_ImageLeft, 28);
    lv_obj_set_align(ui_AltitudeScreen_ImageLeft, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AltitudeScreen_ImageLeft, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_AltitudeScreen_ImageLeft, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AltitudeScreen_LabelLeft = lv_label_create(ui_AltitudeScreen_ContainerLeft);
    lv_obj_set_width(ui_AltitudeScreen_LabelLeft, 90);
    lv_obj_set_height(ui_AltitudeScreen_LabelLeft, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_AltitudeScreen_LabelLeft, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AltitudeScreen_LabelLeft, "long press to exit settings");
    lv_obj_set_style_text_align(ui_AltitudeScreen_LabelLeft, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AltitudeScreen_LabelLeft, &ui_font_Arial_Bold_13, LV_PART_MAIN | LV_STATE_DEFAULT);

}
