// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: Settings

#include "ui.h"

void ui_BrightnessScreen_screen_init(void)
{
    ui_BrightnessScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_BrightnessScreen,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM);     /// Flags
    lv_obj_set_scrollbar_mode(ui_BrightnessScreen, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_scroll_snap_x(ui_BrightnessScreen, LV_SCROLL_SNAP_CENTER);
    lv_obj_set_scroll_snap_y(ui_BrightnessScreen, LV_SCROLL_SNAP_CENTER);
    lv_obj_set_style_bg_color(ui_BrightnessScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BrightnessScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_BrightnessScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_BrightnessScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_BrightnessScreen, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_BrightnessScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BrightnessScreen_Container = lv_obj_create(ui_BrightnessScreen);
    lv_obj_remove_style_all(ui_BrightnessScreen_Container);
    lv_obj_set_width(ui_BrightnessScreen_Container, lv_pct(100));
    lv_obj_set_height(ui_BrightnessScreen_Container, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BrightnessScreen_Container, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_BrightnessScreen_Container, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_BrightnessScreen_Container, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BrightnessScreen_Container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BrightnessScreen_ContainerUp = lv_obj_create(ui_BrightnessScreen_Container);
    lv_obj_remove_style_all(ui_BrightnessScreen_ContainerUp);
    lv_obj_set_width(ui_BrightnessScreen_ContainerUp, 160);
    lv_obj_set_height(ui_BrightnessScreen_ContainerUp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BrightnessScreen_ContainerUp, 23);
    lv_obj_set_y(ui_BrightnessScreen_ContainerUp, -106);
    lv_obj_set_align(ui_BrightnessScreen_ContainerUp, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_BrightnessScreen_ContainerUp, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_BrightnessScreen_ContainerUp, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_BrightnessScreen_ContainerUp, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_BrightnessScreen_ContainerUp, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_BrightnessScreen_ContainerUp, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_BrightnessScreen_ContainerUp, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_BrightnessScreen_ContainerUp, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_BrightnessScreen_ContainerUp, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_BrightnessScreen_ContainerUp, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BrightnessScreen_ContainerUp, &ui_font_Arial_Bold_13, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BrightnessScreen_ImageUp = lv_img_create(ui_BrightnessScreen_ContainerUp);
    lv_img_set_src(ui_BrightnessScreen_ImageUp, &ui_img_816914973);
    lv_obj_set_width(ui_BrightnessScreen_ImageUp, 20);
    lv_obj_set_height(ui_BrightnessScreen_ImageUp, 20);
    lv_obj_set_align(ui_BrightnessScreen_ImageUp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BrightnessScreen_ImageUp, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BrightnessScreen_ImageUp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BrightnessScreen_Panel = lv_obj_create(ui_BrightnessScreen_Container);
    lv_obj_set_width(ui_BrightnessScreen_Panel, 166);
    lv_obj_set_height(ui_BrightnessScreen_Panel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BrightnessScreen_Panel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_BrightnessScreen_Panel, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_BrightnessScreen_Panel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_BrightnessScreen_Panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BrightnessScreen_Panel, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BrightnessScreen_Panel, lv_color_hex(0x182831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BrightnessScreen_Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BrightnessScreen_Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_BrightnessScreen_Panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BrightnessScreen_Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BrightnessScreen_Panel, &ui_font_Arial_Bold_13, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BrightnessScreen_Title = lv_label_create(ui_BrightnessScreen_Panel);
    lv_obj_set_width(ui_BrightnessScreen_Title, lv_pct(100));
    lv_obj_set_height(ui_BrightnessScreen_Title, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BrightnessScreen_Title, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BrightnessScreen_Title, "Screen brigthness");
    lv_obj_set_style_text_align(ui_BrightnessScreen_Title, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BrightnessScreen_Checkbox100 = lv_checkbox_create(ui_BrightnessScreen_Panel);
    lv_checkbox_set_text(ui_BrightnessScreen_Checkbox100, "100%");
    lv_obj_set_width(ui_BrightnessScreen_Checkbox100, lv_pct(100));
    lv_obj_set_height(ui_BrightnessScreen_Checkbox100, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BrightnessScreen_Checkbox100, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_BrightnessScreen_Checkbox100, LV_STATE_CHECKED);       /// States
    lv_obj_add_flag(ui_BrightnessScreen_Checkbox100, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    lv_obj_set_style_radius(ui_BrightnessScreen_Checkbox100, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_BrightnessScreen_Checkbox100, 10, LV_PART_INDICATOR | LV_STATE_CHECKED);
    ui_object_set_themeable_style_property(ui_BrightnessScreen_Checkbox100, LV_PART_INDICATOR | LV_STATE_CHECKED,
                                           LV_STYLE_BG_COLOR, _ui_theme_color_Green);
    ui_object_set_themeable_style_property(ui_BrightnessScreen_Checkbox100, LV_PART_INDICATOR | LV_STATE_CHECKED,
                                           LV_STYLE_BG_OPA, _ui_theme_alpha_Green);
    lv_obj_set_style_border_width(ui_BrightnessScreen_Checkbox100, 0, LV_PART_INDICATOR | LV_STATE_CHECKED);

    ui_BrightnessScreen_Checkbox75 = lv_checkbox_create(ui_BrightnessScreen_Panel);
    lv_checkbox_set_text(ui_BrightnessScreen_Checkbox75, "75%");
    lv_obj_set_width(ui_BrightnessScreen_Checkbox75, lv_pct(100));
    lv_obj_set_height(ui_BrightnessScreen_Checkbox75, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BrightnessScreen_Checkbox75, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BrightnessScreen_Checkbox75, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    lv_obj_set_style_radius(ui_BrightnessScreen_Checkbox75, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_BrightnessScreen_Checkbox75, 10, LV_PART_INDICATOR | LV_STATE_CHECKED);
    ui_object_set_themeable_style_property(ui_BrightnessScreen_Checkbox75, LV_PART_INDICATOR | LV_STATE_CHECKED,
                                           LV_STYLE_BG_COLOR, _ui_theme_color_Green);
    ui_object_set_themeable_style_property(ui_BrightnessScreen_Checkbox75, LV_PART_INDICATOR | LV_STATE_CHECKED,
                                           LV_STYLE_BG_OPA, _ui_theme_alpha_Green);
    lv_obj_set_style_border_width(ui_BrightnessScreen_Checkbox75, 0, LV_PART_INDICATOR | LV_STATE_CHECKED);

    ui_BrightnessScreen_Checkbox50 = lv_checkbox_create(ui_BrightnessScreen_Panel);
    lv_checkbox_set_text(ui_BrightnessScreen_Checkbox50, "50%");
    lv_obj_set_width(ui_BrightnessScreen_Checkbox50, lv_pct(100));
    lv_obj_set_height(ui_BrightnessScreen_Checkbox50, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BrightnessScreen_Checkbox50, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BrightnessScreen_Checkbox50, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    lv_obj_set_style_radius(ui_BrightnessScreen_Checkbox50, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_BrightnessScreen_Checkbox50, 10, LV_PART_INDICATOR | LV_STATE_CHECKED);
    ui_object_set_themeable_style_property(ui_BrightnessScreen_Checkbox50, LV_PART_INDICATOR | LV_STATE_CHECKED,
                                           LV_STYLE_BG_COLOR, _ui_theme_color_Green);
    ui_object_set_themeable_style_property(ui_BrightnessScreen_Checkbox50, LV_PART_INDICATOR | LV_STATE_CHECKED,
                                           LV_STYLE_BG_OPA, _ui_theme_alpha_Green);
    lv_obj_set_style_border_width(ui_BrightnessScreen_Checkbox50, 0, LV_PART_INDICATOR | LV_STATE_CHECKED);

    ui_BrightnessScreen_Checkbox25 = lv_checkbox_create(ui_BrightnessScreen_Panel);
    lv_checkbox_set_text(ui_BrightnessScreen_Checkbox25, "25%");
    lv_obj_set_width(ui_BrightnessScreen_Checkbox25, lv_pct(100));
    lv_obj_set_height(ui_BrightnessScreen_Checkbox25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BrightnessScreen_Checkbox25, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BrightnessScreen_Checkbox25, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    lv_obj_set_style_radius(ui_BrightnessScreen_Checkbox25, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_BrightnessScreen_Checkbox25, 10, LV_PART_INDICATOR | LV_STATE_CHECKED);
    ui_object_set_themeable_style_property(ui_BrightnessScreen_Checkbox25, LV_PART_INDICATOR | LV_STATE_CHECKED,
                                           LV_STYLE_BG_COLOR, _ui_theme_color_Green);
    ui_object_set_themeable_style_property(ui_BrightnessScreen_Checkbox25, LV_PART_INDICATOR | LV_STATE_CHECKED,
                                           LV_STYLE_BG_OPA, _ui_theme_alpha_Green);
    lv_obj_set_style_border_width(ui_BrightnessScreen_Checkbox25, 0, LV_PART_INDICATOR | LV_STATE_CHECKED);

    ui_BrightnessScreen_ContainerDown = lv_obj_create(ui_BrightnessScreen_Container);
    lv_obj_remove_style_all(ui_BrightnessScreen_ContainerDown);
    lv_obj_set_width(ui_BrightnessScreen_ContainerDown, lv_pct(100));
    lv_obj_set_height(ui_BrightnessScreen_ContainerDown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BrightnessScreen_ContainerDown, 23);
    lv_obj_set_y(ui_BrightnessScreen_ContainerDown, -106);
    lv_obj_set_align(ui_BrightnessScreen_ContainerDown, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_BrightnessScreen_ContainerDown, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_BrightnessScreen_ContainerDown, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_BrightnessScreen_ContainerDown, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_BrightnessScreen_ContainerDown, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_BrightnessScreen_ContainerDown, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_BrightnessScreen_ContainerDown, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_BrightnessScreen_ContainerDown, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_BrightnessScreen_ContainerDown, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_BrightnessScreen_ContainerDown, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BrightnessScreen_ContainerDown, &ui_font_Arial_Bold_13, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BrightnessScreen_ImageDown = lv_img_create(ui_BrightnessScreen_ContainerDown);
    lv_img_set_src(ui_BrightnessScreen_ImageDown, &ui_img_blank_png);
    lv_obj_set_width(ui_BrightnessScreen_ImageDown, 20);
    lv_obj_set_height(ui_BrightnessScreen_ImageDown, 20);
    lv_obj_set_align(ui_BrightnessScreen_ImageDown, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BrightnessScreen_ImageDown, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BrightnessScreen_ImageDown, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BrightnessScreen_ContainerRight = lv_obj_create(ui_BrightnessScreen);
    lv_obj_remove_style_all(ui_BrightnessScreen_ContainerRight);
    lv_obj_set_width(ui_BrightnessScreen_ContainerRight, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BrightnessScreen_ContainerRight, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BrightnessScreen_ContainerRight, -5);
    lv_obj_set_y(ui_BrightnessScreen_ContainerRight, -5);
    lv_obj_set_align(ui_BrightnessScreen_ContainerRight, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_set_flex_flow(ui_BrightnessScreen_ContainerRight, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_BrightnessScreen_ContainerRight, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_BrightnessScreen_ContainerRight, LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags
    lv_obj_clear_flag(ui_BrightnessScreen_ContainerRight, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BrightnessScreen_LabelRight = lv_label_create(ui_BrightnessScreen_ContainerRight);
    lv_obj_set_width(ui_BrightnessScreen_LabelRight, 86);
    lv_obj_set_height(ui_BrightnessScreen_LabelRight, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BrightnessScreen_LabelRight, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BrightnessScreen_LabelRight, "long press to adjust value");
    lv_obj_set_style_text_align(ui_BrightnessScreen_LabelRight, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BrightnessScreen_LabelRight, &ui_font_Arial_Bold_13, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BrightnessScreen_ImageRight = lv_img_create(ui_BrightnessScreen_ContainerRight);
    lv_img_set_src(ui_BrightnessScreen_ImageRight, &ui_img_718623388);
    lv_obj_set_width(ui_BrightnessScreen_ImageRight, 28);
    lv_obj_set_height(ui_BrightnessScreen_ImageRight, 28);
    lv_obj_set_align(ui_BrightnessScreen_ImageRight, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BrightnessScreen_ImageRight, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BrightnessScreen_ImageRight, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BrightnessScreen_ContainerLeft = lv_obj_create(ui_BrightnessScreen);
    lv_obj_remove_style_all(ui_BrightnessScreen_ContainerLeft);
    lv_obj_set_width(ui_BrightnessScreen_ContainerLeft, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BrightnessScreen_ContainerLeft, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BrightnessScreen_ContainerLeft, 5);
    lv_obj_set_y(ui_BrightnessScreen_ContainerLeft, -40);
    lv_obj_set_align(ui_BrightnessScreen_ContainerLeft, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_set_flex_flow(ui_BrightnessScreen_ContainerLeft, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_BrightnessScreen_ContainerLeft, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_BrightnessScreen_ContainerLeft, LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags
    lv_obj_clear_flag(ui_BrightnessScreen_ContainerLeft, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_BrightnessScreen_ContainerLeft, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_BrightnessScreen_ContainerLeft, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BrightnessScreen_ImageLeft = lv_img_create(ui_BrightnessScreen_ContainerLeft);
    lv_img_set_src(ui_BrightnessScreen_ImageLeft, &ui_img_1346862293);
    lv_obj_set_width(ui_BrightnessScreen_ImageLeft, 28);
    lv_obj_set_height(ui_BrightnessScreen_ImageLeft, 28);
    lv_obj_set_align(ui_BrightnessScreen_ImageLeft, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BrightnessScreen_ImageLeft, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BrightnessScreen_ImageLeft, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BrightnessScreen_LabelLeft = lv_label_create(ui_BrightnessScreen_ContainerLeft);
    lv_obj_set_width(ui_BrightnessScreen_LabelLeft, 90);
    lv_obj_set_height(ui_BrightnessScreen_LabelLeft, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BrightnessScreen_LabelLeft, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BrightnessScreen_LabelLeft, "long press to exit settings");
    lv_obj_set_style_text_align(ui_BrightnessScreen_LabelLeft, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BrightnessScreen_LabelLeft, &ui_font_Arial_Bold_13, LV_PART_MAIN | LV_STATE_DEFAULT);

}
