// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: Settings

#include "ui.h"

void ui_ChartTimeScreen_screen_init(void)
{
    ui_ChartTimeScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ChartTimeScreen,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM);     /// Flags
    lv_obj_set_scrollbar_mode(ui_ChartTimeScreen, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_scroll_snap_x(ui_ChartTimeScreen, LV_SCROLL_SNAP_CENTER);
    lv_obj_set_scroll_snap_y(ui_ChartTimeScreen, LV_SCROLL_SNAP_CENTER);
    lv_obj_set_style_bg_color(ui_ChartTimeScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ChartTimeScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ChartTimeScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ChartTimeScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ChartTimeScreen, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ChartTimeScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ChartTimeScreen_Container = lv_obj_create(ui_ChartTimeScreen);
    lv_obj_remove_style_all(ui_ChartTimeScreen_Container);
    lv_obj_set_width(ui_ChartTimeScreen_Container, lv_pct(100));
    lv_obj_set_height(ui_ChartTimeScreen_Container, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ChartTimeScreen_Container, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_ChartTimeScreen_Container, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_ChartTimeScreen_Container, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ChartTimeScreen_Container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ChartTimeScreen_ContainerUp = lv_obj_create(ui_ChartTimeScreen_Container);
    lv_obj_remove_style_all(ui_ChartTimeScreen_ContainerUp);
    lv_obj_set_width(ui_ChartTimeScreen_ContainerUp, 160);
    lv_obj_set_height(ui_ChartTimeScreen_ContainerUp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ChartTimeScreen_ContainerUp, 23);
    lv_obj_set_y(ui_ChartTimeScreen_ContainerUp, -106);
    lv_obj_set_align(ui_ChartTimeScreen_ContainerUp, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ChartTimeScreen_ContainerUp, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ChartTimeScreen_ContainerUp, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_ChartTimeScreen_ContainerUp, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_ChartTimeScreen_ContainerUp, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ChartTimeScreen_ContainerUp, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ChartTimeScreen_ContainerUp, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ChartTimeScreen_ContainerUp, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_ChartTimeScreen_ContainerUp, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ChartTimeScreen_ContainerUp, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ChartTimeScreen_ContainerUp, &ui_font_Arial_Bold_13, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ChartTimeScreen_ImageUp = lv_img_create(ui_ChartTimeScreen_ContainerUp);
    lv_img_set_src(ui_ChartTimeScreen_ImageUp, &ui_img_816914973);
    lv_obj_set_width(ui_ChartTimeScreen_ImageUp, 20);
    lv_obj_set_height(ui_ChartTimeScreen_ImageUp, 20);
    lv_obj_set_align(ui_ChartTimeScreen_ImageUp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ChartTimeScreen_ImageUp, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ChartTimeScreen_ImageUp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ChartTimeScreen_Panel = lv_obj_create(ui_ChartTimeScreen_Container);
    lv_obj_set_width(ui_ChartTimeScreen_Panel, 166);
    lv_obj_set_height(ui_ChartTimeScreen_Panel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ChartTimeScreen_Panel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ChartTimeScreen_Panel, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_ChartTimeScreen_Panel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_ChartTimeScreen_Panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ChartTimeScreen_Panel, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ChartTimeScreen_Panel, lv_color_hex(0x182831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ChartTimeScreen_Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ChartTimeScreen_Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_ChartTimeScreen_Panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ChartTimeScreen_Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ChartTimeScreen_Panel, &ui_font_Arial_Bold_13, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ChartTimeScreen_Title = lv_label_create(ui_ChartTimeScreen_Panel);
    lv_obj_set_width(ui_ChartTimeScreen_Title, lv_pct(100));
    lv_obj_set_height(ui_ChartTimeScreen_Title, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ChartTimeScreen_Title, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ChartTimeScreen_Title, "Displayed time on the charts");
    lv_obj_set_style_text_align(ui_ChartTimeScreen_Title, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ChartTimeScreen_CheckboxShort = lv_checkbox_create(ui_ChartTimeScreen_Panel);
    lv_checkbox_set_text(ui_ChartTimeScreen_CheckboxShort, "2min30");
    lv_obj_set_width(ui_ChartTimeScreen_CheckboxShort, lv_pct(100));
    lv_obj_set_height(ui_ChartTimeScreen_CheckboxShort, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ChartTimeScreen_CheckboxShort, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ChartTimeScreen_CheckboxShort, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    lv_obj_set_style_radius(ui_ChartTimeScreen_CheckboxShort, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ChartTimeScreen_CheckboxShort, 10, LV_PART_INDICATOR | LV_STATE_CHECKED);
    ui_object_set_themeable_style_property(ui_ChartTimeScreen_CheckboxShort, LV_PART_INDICATOR | LV_STATE_CHECKED,
                                           LV_STYLE_BG_COLOR, _ui_theme_color_Green);
    ui_object_set_themeable_style_property(ui_ChartTimeScreen_CheckboxShort, LV_PART_INDICATOR | LV_STATE_CHECKED,
                                           LV_STYLE_BG_OPA, _ui_theme_alpha_Green);
    lv_obj_set_style_border_width(ui_ChartTimeScreen_CheckboxShort, 0, LV_PART_INDICATOR | LV_STATE_CHECKED);

    ui_ChartTimeScreen_CheckboxMedium = lv_checkbox_create(ui_ChartTimeScreen_Panel);
    lv_checkbox_set_text(ui_ChartTimeScreen_CheckboxMedium, "60min");
    lv_obj_set_width(ui_ChartTimeScreen_CheckboxMedium, lv_pct(100));
    lv_obj_set_height(ui_ChartTimeScreen_CheckboxMedium, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ChartTimeScreen_CheckboxMedium, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_ChartTimeScreen_CheckboxMedium, LV_STATE_CHECKED);       /// States
    lv_obj_add_flag(ui_ChartTimeScreen_CheckboxMedium, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    lv_obj_set_style_radius(ui_ChartTimeScreen_CheckboxMedium, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ChartTimeScreen_CheckboxMedium, 10, LV_PART_INDICATOR | LV_STATE_CHECKED);
    ui_object_set_themeable_style_property(ui_ChartTimeScreen_CheckboxMedium, LV_PART_INDICATOR | LV_STATE_CHECKED,
                                           LV_STYLE_BG_COLOR, _ui_theme_color_Green);
    ui_object_set_themeable_style_property(ui_ChartTimeScreen_CheckboxMedium, LV_PART_INDICATOR | LV_STATE_CHECKED,
                                           LV_STYLE_BG_OPA, _ui_theme_alpha_Green);
    lv_obj_set_style_border_width(ui_ChartTimeScreen_CheckboxMedium, 0, LV_PART_INDICATOR | LV_STATE_CHECKED);

    ui_ChartTimeScreen_CheckboxLong = lv_checkbox_create(ui_ChartTimeScreen_Panel);
    lv_checkbox_set_text(ui_ChartTimeScreen_CheckboxLong, "24h");
    lv_obj_set_width(ui_ChartTimeScreen_CheckboxLong, lv_pct(100));
    lv_obj_set_height(ui_ChartTimeScreen_CheckboxLong, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ChartTimeScreen_CheckboxLong, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ChartTimeScreen_CheckboxLong, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    lv_obj_set_style_radius(ui_ChartTimeScreen_CheckboxLong, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ChartTimeScreen_CheckboxLong, 10, LV_PART_INDICATOR | LV_STATE_CHECKED);
    ui_object_set_themeable_style_property(ui_ChartTimeScreen_CheckboxLong, LV_PART_INDICATOR | LV_STATE_CHECKED,
                                           LV_STYLE_BG_COLOR, _ui_theme_color_Green);
    ui_object_set_themeable_style_property(ui_ChartTimeScreen_CheckboxLong, LV_PART_INDICATOR | LV_STATE_CHECKED,
                                           LV_STYLE_BG_OPA, _ui_theme_alpha_Green);
    lv_obj_set_style_border_width(ui_ChartTimeScreen_CheckboxLong, 0, LV_PART_INDICATOR | LV_STATE_CHECKED);

    ui_ChartTimeScreen_ContainerDown = lv_obj_create(ui_ChartTimeScreen_Container);
    lv_obj_remove_style_all(ui_ChartTimeScreen_ContainerDown);
    lv_obj_set_width(ui_ChartTimeScreen_ContainerDown, lv_pct(100));
    lv_obj_set_height(ui_ChartTimeScreen_ContainerDown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ChartTimeScreen_ContainerDown, 23);
    lv_obj_set_y(ui_ChartTimeScreen_ContainerDown, -106);
    lv_obj_set_align(ui_ChartTimeScreen_ContainerDown, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ChartTimeScreen_ContainerDown, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ChartTimeScreen_ContainerDown, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_ChartTimeScreen_ContainerDown, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_ChartTimeScreen_ContainerDown, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ChartTimeScreen_ContainerDown, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ChartTimeScreen_ContainerDown, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ChartTimeScreen_ContainerDown, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_ChartTimeScreen_ContainerDown, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ChartTimeScreen_ContainerDown, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ChartTimeScreen_ContainerDown, &ui_font_Arial_Bold_13, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ChartTimeScreen_ImageDown = lv_img_create(ui_ChartTimeScreen_ContainerDown);
    lv_img_set_src(ui_ChartTimeScreen_ImageDown, &ui_img_810620936);
    lv_obj_set_width(ui_ChartTimeScreen_ImageDown, 20);
    lv_obj_set_height(ui_ChartTimeScreen_ImageDown, 20);
    lv_obj_set_align(ui_ChartTimeScreen_ImageDown, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ChartTimeScreen_ImageDown, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ChartTimeScreen_ImageDown, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ChartTimeScreen_ContainerRight = lv_obj_create(ui_ChartTimeScreen);
    lv_obj_remove_style_all(ui_ChartTimeScreen_ContainerRight);
    lv_obj_set_width(ui_ChartTimeScreen_ContainerRight, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ChartTimeScreen_ContainerRight, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ChartTimeScreen_ContainerRight, -5);
    lv_obj_set_y(ui_ChartTimeScreen_ContainerRight, -5);
    lv_obj_set_align(ui_ChartTimeScreen_ContainerRight, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_set_flex_flow(ui_ChartTimeScreen_ContainerRight, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ChartTimeScreen_ContainerRight, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_ChartTimeScreen_ContainerRight, LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags
    lv_obj_clear_flag(ui_ChartTimeScreen_ContainerRight, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ChartTimeScreen_LabelRight = lv_label_create(ui_ChartTimeScreen_ContainerRight);
    lv_obj_set_width(ui_ChartTimeScreen_LabelRight, 86);
    lv_obj_set_height(ui_ChartTimeScreen_LabelRight, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ChartTimeScreen_LabelRight, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ChartTimeScreen_LabelRight, "long press to adjust value");
    lv_obj_set_style_text_align(ui_ChartTimeScreen_LabelRight, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ChartTimeScreen_LabelRight, &ui_font_Arial_Bold_13, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ChartTimeScreen_ImageRight = lv_img_create(ui_ChartTimeScreen_ContainerRight);
    lv_img_set_src(ui_ChartTimeScreen_ImageRight, &ui_img_718623388);
    lv_obj_set_width(ui_ChartTimeScreen_ImageRight, 28);
    lv_obj_set_height(ui_ChartTimeScreen_ImageRight, 28);
    lv_obj_set_align(ui_ChartTimeScreen_ImageRight, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ChartTimeScreen_ImageRight, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ChartTimeScreen_ImageRight, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ChartTimeScreen_ContainerLeft = lv_obj_create(ui_ChartTimeScreen);
    lv_obj_remove_style_all(ui_ChartTimeScreen_ContainerLeft);
    lv_obj_set_width(ui_ChartTimeScreen_ContainerLeft, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ChartTimeScreen_ContainerLeft, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ChartTimeScreen_ContainerLeft, 5);
    lv_obj_set_y(ui_ChartTimeScreen_ContainerLeft, -40);
    lv_obj_set_align(ui_ChartTimeScreen_ContainerLeft, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_set_flex_flow(ui_ChartTimeScreen_ContainerLeft, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ChartTimeScreen_ContainerLeft, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_ChartTimeScreen_ContainerLeft, LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags
    lv_obj_clear_flag(ui_ChartTimeScreen_ContainerLeft, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_ChartTimeScreen_ContainerLeft, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ChartTimeScreen_ContainerLeft, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ChartTimeScreen_ImageLeft = lv_img_create(ui_ChartTimeScreen_ContainerLeft);
    lv_img_set_src(ui_ChartTimeScreen_ImageLeft, &ui_img_1346862293);
    lv_obj_set_width(ui_ChartTimeScreen_ImageLeft, 28);
    lv_obj_set_height(ui_ChartTimeScreen_ImageLeft, 28);
    lv_obj_set_align(ui_ChartTimeScreen_ImageLeft, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ChartTimeScreen_ImageLeft, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ChartTimeScreen_ImageLeft, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ChartTimeScreen_LabelLeft = lv_label_create(ui_ChartTimeScreen_ContainerLeft);
    lv_obj_set_width(ui_ChartTimeScreen_LabelLeft, 90);
    lv_obj_set_height(ui_ChartTimeScreen_LabelLeft, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ChartTimeScreen_LabelLeft, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ChartTimeScreen_LabelLeft, "long press to exit settings");
    lv_obj_set_style_text_align(ui_ChartTimeScreen_LabelLeft, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ChartTimeScreen_LabelLeft, &ui_font_Arial_Bold_13, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ChartTimeScreen_PanelInfo2 = lv_obj_create(ui_ChartTimeScreen);
    lv_obj_set_width(ui_ChartTimeScreen_PanelInfo2, 170);
    lv_obj_set_height(ui_ChartTimeScreen_PanelInfo2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ChartTimeScreen_PanelInfo2, 0);
    lv_obj_set_y(ui_ChartTimeScreen_PanelInfo2, 60);
    lv_obj_set_align(ui_ChartTimeScreen_PanelInfo2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ChartTimeScreen_PanelInfo2, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_ChartTimeScreen_PanelInfo2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_END);
    lv_obj_clear_flag(ui_ChartTimeScreen_PanelInfo2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ChartTimeScreen_PanelInfo2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ChartTimeScreen_PanelInfo2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ChartTimeScreen_PanelInfo2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ChartTimeScreen_PanelInfo2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ChartTimeScreen_PanelInfo2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ChartTimeScreen_PanelInfo2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ChartTimeScreen_PanelInfo2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ChartTimeScreen_PanelInfo2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ChartTimeScreen_PanelInfo2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ChartTimeScreen_LabelInfo2 = lv_label_create(ui_ChartTimeScreen_PanelInfo2);
    lv_obj_set_width(ui_ChartTimeScreen_LabelInfo2, 170);
    lv_obj_set_height(ui_ChartTimeScreen_LabelInfo2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ChartTimeScreen_LabelInfo2, 0);
    lv_obj_set_y(ui_ChartTimeScreen_LabelInfo2, 30);
    lv_obj_set_align(ui_ChartTimeScreen_LabelInfo2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ChartTimeScreen_LabelInfo2, "Info: Long press right button on any chart to change this setting.");
    lv_obj_set_style_text_align(ui_ChartTimeScreen_LabelInfo2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ChartTimeScreen_LabelInfo2, &ui_font_Arial_Bold_13, LV_PART_MAIN | LV_STATE_DEFAULT);

}
