// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: Settings

#ifndef _UI_COMP_TILE_H
#define _UI_COMP_TILE_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Tile
#define UI_COMP_TILE_TILE 0
#define UI_COMP_TILE_VALUE 1
#define UI_COMP_TILE_INDICATOR 2
#define UI_COMP_TILE_POLUTANT 3
#define UI_COMP_TILE_UNIT 4
#define UI_COMP_TILE_SYMBOL 5
#define _UI_COMP_TILE_NUM 6
lv_obj_t * ui_Tile_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
